<script setup lang="ts">
import {t} from "../i18n"
import { computed, ref } from 'vue'
import { useCms } from '../store'
import Icon from './Icon.vue'
const props = defineProps<{view:string}>()
const emit = defineEmits(['create','manage','navigate'])
const cms = useCms(), filter = ref('All websites'), query = ref(''), layout = ref('grid')
const sites = computed(() => cms.websites.filter(s => (filter.value === 'All websites' || s.status === filter.value.toLowerCase()) && (s.name+' '+s.domain).toLowerCase().includes(query.value.toLowerCase())))
const visibleSites = computed(() => props.view === 'Overview' ? sites.value.slice(0,3) : sites.value)
const metrics = computed(() => [{label:'Total websites',value:cms.counts.websites,icon:'PanelsTopLeft',note:'All your ideas, in one place',tag:'Your workspace'},{label:'Published pages',value:cms.counts.published,icon:'FileCheck2',note:'Live and ready for the world',tag:'Looking good',green:true},{label:'Media assets',value:cms.counts.media,icon:'Images',note:'A library of possibilities',tag:'Ready to use'},{label:'Draft pages',value:cms.counts.drafts,icon:'FilePenLine',note:'Great things in the making',tag:'Keep creating',amber:true}])
function visit(id:number){window.open('/site/'+id+'/home','_blank','noopener')}
</script>
<template>
<div class="dashboard page-wrap">
<div class="page-heading"><div><div class="eyebrow">{{ $t(view === 'Overview' ? 'YOUR WORKSPACE, AT A GLANCE' : 'A HOME FOR EVERY IDEA') }}</div><h1>{{ $t(view === 'Overview' ? 'Good afternoon, Alex' : 'Your websites') }}<span v-if="view === 'Overview'" class="greeting-dot">.</span></h1><p>{{ $t(view === 'Overview' ? 'A little overview of everything you’re bringing to life.' : 'Create, manage, and grow every website from one place.') }}</p></div><button class="btn primary" @click="emit('create')"><Icon name="Plus" :size="18"/>{{ $t("Create website") }}</button></div>
<section v-if="view === 'Overview'" class="welcome-banner"><div class="welcome-copy"><span class="pill"><span class="status-dot"></span> {{ $t("A SPACE FOR YOUR NEXT BIG THING") }}</span><h2>{{ $t("Many websites.") }}<br>{{ $t("One beautiful workspace.") }}</h2><p>{{ $t("From first idea to live website. Everything you need,") }}<br class="desktop-break"> {{ $t("thoughtfully brought together.") }}</p><button @click="emit('create')">{{ $t("Let’s build something") }} <Icon name="ArrowRight" :size="17"/></button></div><div class="welcome-art" aria-hidden="true"><span class="orbit orbit-one"></span><span class="orbit orbit-two"></span><span class="floating-square square-one"><Icon name="MousePointer2" :size="23"/></span><span class="floating-square square-two"><Icon name="Palette" :size="23"/></span><span class="art-spark">✳</span><div class="art-browser browser-back"><div class="browser-chrome"><i></i><i></i><i></i></div><div class="back-lines"><span></span><span></span><span></span></div></div><div class="art-browser browser-front"><div class="browser-chrome"><i></i><i></i><i></i><span>{{ $t("your next great idea") }}</span><Icon name="LockKeyhole" :size="8"/></div><div class="mini-brand">{{ $t("your brand") }}<span>Explore&nbsp; &nbsp; About&nbsp; &nbsp; Contact</span></div><div class="art-web-content"><div><small>{{ $t("MADE TO MAKE AN IMPACT") }}</small><h3>{{ $t("Something") }}<br>{{ $t("extraordinary") }}<br>{{ $t("starts here.") }}</h3><span class="mini-button">{{ $t("Discover more ↗") }}</span></div><div class="arch-photo"></div></div><div class="mini-bottom"><i></i><i></i><i></i></div></div><span class="live-tag"><span class="status-dot"></span> {{ $t("Ready when you are") }}</span></div></section>
<section class="metrics-grid" v-if="view === 'Overview'"><article v-for="metric in metrics" :key="metric.label" class="metric-card"><div class="metric-top"><span>{{ $t(metric.label) }}</span><Icon :name="metric.icon" :size="19"/></div><div class="metric-value">{{ metric.value ?? '—' }}<span :class="['metric-tag', {green:metric.green, amber:metric.amber}]">{{ $t(metric.tag) }}</span></div><p>{{ $t(metric.note) }}</p></article></section>
<section class="websites-section"><div class="section-heading"><div class="section-title"><h2>{{ $t(view === 'Overview' ? 'Your websites' : 'All websites') }}</h2><span class="count-badge">{{ cms.websites.length }}</span></div><button class="text-link" v-if="view === 'Overview'" @click="emit('navigate','Websites')">{{ $t("View all websites") }} <Icon name="ArrowRight" :size="16"/></button></div><div class="website-toolbar"><div class="filter-tabs"><button v-for="tab in ['All websites','Published','Draft']" :class="{active:filter===tab}" @click="filter=tab">{{ $t(tab) }}<span v-if="tab==='All websites'">{{ cms.websites.length }}</span><span v-else>{{ cms.websites.filter(s=>s.status===tab.toLowerCase()).length }}</span></button></div><div class="website-tools"><div class="inline-search"><Icon name="Search" :size="16"/><input v-model="query" :placeholder="$t('Find a website...')" :aria-label="$t('Find a website')"></div><div class="view-toggle"><button :class="{active:layout==='grid'}" @click="layout='grid'" :aria-label="$t('Grid view')"><Icon name="LayoutGrid" :size="16"/></button><button :class="{active:layout==='list'}" @click="layout='list'" :aria-label="$t('List view')"><Icon name="List" :size="18"/></button></div></div></div>
<div :class="['website-grid', { 'website-list':layout==='list' }]"><article v-for="(site, index) in visibleSites" :key="site.id" class="website-card"><div class="site-preview" :class="'preview-'+(site.type === 'University' ? 'university' : site.type === 'E-commerce' ? 'shop' : 'studio')" @click="emit('manage',site.id)"><div class="preview-site-nav"><strong>{{ site.name }}</strong><span>About &nbsp; Collection &nbsp; <Icon name="Menu" :size="8"/></span></div><div class="preview-content"><div class="preview-photo" :style="{ backgroundImage:`url(${site.image})` }"></div><div class="preview-copy"><small>{{ $t(site.type === 'University' ? 'EXPLORE YOUR POTENTIAL' : site.type === 'E-commerce' ? 'THOUGHTFUL LIVING' : 'SPACES THAT TELL A STORY') }}</small><h3>{{ $t(site.type === 'University' ? 'Your future.\nWithout limits.' : site.type === 'E-commerce' ? 'Less,\nbut better.' : 'Thoughtfully\ndesigned.\nNaturally you.') }}</h3><span>{{ $t(site.type === 'University' ? 'Discover Westbridge' : site.type === 'E-commerce' ? 'Explore the collection' : 'Explore our work') }} ↗</span></div></div><span class="preview-open"><Icon name="ArrowUpRight" :size="17"/></span></div><div class="site-card-body"><div class="site-title-row"><span class="site-letter" :style="{background:site.color+'15', color:site.color}"><Icon :name="site.type==='University'?'GraduationCap':site.type==='E-commerce'?'ShoppingBag':'Leaf'" :size="20"/></span><div><h3>{{ site.name }}</h3><a :href="'/site/'+site.id+'/home'" target="_blank">{{ site.domain }} <Icon name="ArrowUpRight" :size="11"/></a></div><q-btn flat round dense size="sm" :aria-label="$t('Website options')"><Icon name="Ellipsis" :size="19"/><q-menu><q-list style="min-width:180px"><q-item clickable v-close-popup @click="emit('manage',site.id,'Settings')"><q-item-section>{{ $t("Website settings") }}</q-item-section></q-item><q-item clickable v-close-popup @click="emit('manage',site.id,'Theme & Appearance')"><q-item-section>{{ $t("Customize appearance") }}</q-item-section></q-item></q-list></q-menu></q-btn></div><div class="site-meta"><span :class="['status-pill',site.status]"><i></i>{{ $t(site.status) }}</span><span>{{ $t(site.type) }}</span><span class="meta-dot">·</span><span>{{ site.pages_count }} {{ $t("pages") }}</span></div><div class="site-card-footer"><span><Icon name="Clock3" :size="13"/>{{ $t(index===0?'Recently edited':'Ready to explore') }}</span><button @click="emit('manage',site.id)">{{ $t("Manage site") }} <Icon name="ArrowRight" :size="14"/></button></div></div></article></div>
<div v-if="!visibleSites.length" class="empty-state"><Icon name="PanelsTopLeft" :size="36"/><h3>{{ $t("No websites here yet.") }}</h3><p>{{ $t(query ? 'Try a different search or filter.' : 'Your next big idea deserves a home.') }}</p><button class="btn primary" @click="emit('create')">{{ $t("Create a website") }}</button></div>
</section>
<div class="dashboard-bottom" v-if="view==='Overview'"><section class="activity-card"><div class="section-heading"><h2>{{ $t("Recent activity") }}</h2><button class="text-link" @click="emit('navigate','Activity log')">{{ $t("View all") }} <Icon name="ArrowRight" :size="15"/></button></div><div v-for="a in cms.activity.slice(0,3)" :key="a.id" class="activity-row"><span class="activity-icon"><Icon :name="a.action.includes('publish')?'Check':a.action.includes('media')?'ImagePlus':'FilePenLine'" :size="16"/></span><div><p><strong>{{ $t(a.user?.split(' ')[0] || 'System') }}</strong> {{ $t(a.action) }} <strong>{{ a.subject }}</strong></p><small>{{ new Date(a.created_at).toLocaleDateString('en',{month:'short',day:'numeric'}) }} · {{ $t(cms.websites.find(s=>s.id===a.website_id)?.name || 'Workspace') }}</small></div><span class="tiny-avatar">{{ (a.user||'System').split(' ').map((s:string)=>s[0]).join('') }}</span></div></section><section class="quick-card"><div class="section-heading"><h2>{{ $t("A little head start") }}</h2><Icon name="Sparkles" :size="19"/></div><p>{{ $t("Less setup. More creating.") }}</p><button @click="emit('navigate','Templates')"><span class="quick-icon peach"><Icon name="PanelsTopLeft" :size="20"/></span><span><strong>{{ $t("Start with a template") }}</strong><small>{{ $t("A thoughtful foundation for your ideas") }}</small></span><Icon name="ArrowUpRight" :size="16"/></button><button @click="emit('navigate','Media library')"><span class="quick-icon lavender"><Icon name="Images" :size="20"/></span><span><strong>{{ $t("Make room for inspiration") }}</strong><small>{{ $t("Upload and organize your media") }}</small></span><Icon name="ArrowUpRight" :size="16"/></button></section></div>
</div>
</template>
