<script setup lang="ts">
import {t} from "../i18n"
import {ref,computed,reactive} from 'vue'
import {useQuasar} from 'quasar'
import {api,send} from '../api'
import type{Media}from '../types'
import Icon from './Icon.vue'
const props=defineProps<{media:Media;siteId:number}>(),emit=defineEmits(['saved','close']),q=useQuasar(),saving=ref(false),natural=ref({width:props.media.width||1,height:props.media.height||1})
const form=reactive({x:0,y:0,crop_width:100,crop_height:100,width:Math.min(props.media.width||1200,4096),quality:85,format:'webp',name:props.media.name.replace(/\.[^.]+$/,'')+'-edited'})
const height=computed(()=>Math.max(1,Math.round(form.width*(natural.value.height*form.crop_height)/(natural.value.width*form.crop_width))))
const invalid=computed(()=>form.x+form.crop_width>100||form.y+form.crop_height>100||height.value>4096||height.value*form.width>4000000)
function reset(){form.x=0;form.y=0;form.crop_width=100;form.crop_height=100}
async function save(){saving.value=true;try{const m=await api('/websites/'+props.siteId+'/media/'+props.media.id+'/transform',send('POST',form));emit('saved',m);q.notify({type:'positive',message:t('Edited copy saved. The original image is unchanged.')})}catch(e:any){q.notify({type:'negative',message:t(e.message)})}finally{saving.value=false}}
</script>
<template><q-card class="image-edit-dialog"><div class="dialog-heading"><div><span class="eyebrow">{{ $t("CROP · RESIZE · OPTIMIZE") }}</span><h2>{{ $t("Find the perfect frame.") }}</h2></div><button class="icon-btn" @click="emit('close')" :aria-label="$t('Close image editor')"><Icon name="X"/></button></div><div class="image-edit-layout"><section><div class="crop-frame"><img :src="media.url" :alt="media.alt" @load="natural={width:($event.target as HTMLImageElement).naturalWidth,height:($event.target as HTMLImageElement).naturalHeight}"><div class="crop-selection" :style="{left:form.x+'%',top:form.y+'%',width:form.crop_width+'%',height:form.crop_height+'%'}"><span>{{ form.crop_width }}% × {{ form.crop_height }}%</span></div></div><p class="muted">{{ $t("Original:") }} {{ natural.width }} × {{ natural.height }} {{ $t("px. All edits are saved as a new media item.") }}</p><button class="text-link" @click="reset"><Icon name="RotateCcw" :size="15"/>{{ $t("Reset crop") }}</button></section><section><label class="field-label">{{ $t("Horizontal position ·") }} {{ form.x }}%</label><q-slider v-model="form.x" :min="0" :max="100-form.crop_width"/><label class="field-label">{{ $t("Vertical position ·") }} {{ form.y }}%</label><q-slider v-model="form.y" :min="0" :max="100-form.crop_height"/><label class="field-label">{{ $t("Crop width ·") }} {{ form.crop_width }}%</label><q-slider v-model="form.crop_width" :min="1" :max="100-form.x"/><label class="field-label">{{ $t("Crop height ·") }} {{ form.crop_height }}%</label><q-slider v-model="form.crop_height" :min="1" :max="100-form.y"/><q-input outlined v-model.number="form.width" type="number" min="16" max="4096" :label="$t('Output width (pixels)')"/><div class="form-two"><q-select emit-value map-options outlined v-model="form.format" :options="$translatedOptions(['webp','jpeg','png'])" :label="$t('Output format')"/><q-input outlined v-model.number="form.quality" type="number" min="20" max="100" :disable="form.format==='png'" :label="$t('Quality (20–100)')"/></div><q-input outlined v-model="form.name" :label="$t('New file name')" maxlength="180"/><small :class="invalid?'text-negative':'muted'">{{ $t("Output:") }} {{ form.width }} × {{ height }} {{ $t("px · Maximum 4 MP and 4096 px per edge") }}</small></section></div><div class="dialog-footer"><span>{{ $t("JPG / PNG / WEBP · No original files are overwritten") }}</span><q-btn color="primary" unelevated :label="$t('Save edited copy')" :disable="invalid || !form.name.trim()" :loading="saving" @click="save"/></div></q-card></template>
