<script setup lang="ts">
import{ref,watch}from'vue'
import{useCms}from'../store'
import{api,send}from'../api'
import{useQuasar}from'quasar'
import{t,appLocale}from'../i18n'
const cms=useCms(),q=useQuasar(),data=ref<any>(null),error=ref(''),page=ref(1),busy=ref(false)
async function load(){if(!cms.selectedId)return;error.value='';try{data.value=await api(`/websites/${cms.selectedId}/inbox?messages_page=${page.value}&subscribers_page=${page.value}`)}catch(e:any){error.value=e.message}}
watch(()=>cms.selectedId,()=>{page.value=1;load()},{immediate:true})
async function status(m:any,value:string){busy.value=true;try{await api(`/websites/${cms.selectedId}/submissions/${m.id}`,send('PUT',{status:value}));await load()}catch(e:any){q.notify({type:'negative',message:t(e.message)})}finally{busy.value=false}}
function remove(kind:string,id:number){q.dialog({title:t('Delete permanently?'),message:t('This removes personal data and cannot be undone.'),cancel:true}).onOk(async()=>{try{await api(`/websites/${cms.selectedId}/engagement/${kind}/${id}`,{method:'DELETE'});await load()}catch(e:any){q.notify({type:'negative',message:t(e.message)})}})}
</script>
<template><section class="panel"><h2>{{ $t('Inbox') }}</h2><p>{{ $t('Contact messages and confirmed newsletter subscriptions for this website.') }}</p><p v-if="error" role="alert">{{ $t(error) }}</p><template v-if="data"><h3>{{ $t('Messages') }} · {{ data.messages.total }}</h3><p v-if="!data.messages.data.length">{{ $t('No messages yet.') }}</p><article class="inbox-message" v-for="m in data.messages.data" :key="m.id"><header><strong>{{ m.name }}</strong> · <a :href="'mailto:'+m.email">{{ m.email }}</a><small>{{ new Date(m.created_at).toLocaleString(appLocale) }}</small></header><p class="preserve-text">{{ m.message }}</p><div class="action-row"><span>{{ $t(m.status) }}</span><button class="btn secondary" :disabled="busy" @click="status(m,m.status==='read'?'archived':'read')">{{ $t(m.status==='read'?'Archive':'Mark read') }}</button><button class="text-link danger" @click="remove('submissions',m.id)">{{ $t('Delete') }}</button></div></article><h3>{{ $t('Newsletter subscribers') }} · {{ data.subscribers.total }}</h3><p>{{ $t('Only confirmed subscribers may receive newsletters. Request a new email from the public form to manage a subscription.') }}</p><div class="table-scroll"><table class="commerce-table"><thead><tr><th>{{ $t('Email address') }}</th><th>{{ $t('Language') }}</th><th>{{ $t('Status') }}</th><th>{{ $t('Actions') }}</th></tr></thead><tbody><tr v-for="s in data.subscribers.data" :key="s.id"><td>{{ s.email }}<a v-if="s.preview_email_url" :href="s.preview_email_url" target="_blank" rel="noopener"> · {{ $t('Preview verification email') }}</a></td><td>{{ s.language }}</td><td>{{ $t(s.status) }}</td><td><button class="text-link danger" @click="remove('subscribers',s.id)">{{ $t('Delete') }}</button></td></tr></tbody></table></div><div class="action-row"><button class="btn secondary" :disabled="page===1" @click="page--;load()">{{ $t('Previous') }}</button><span>{{ page }}</span><button class="btn secondary" :disabled="!data.messages.next_page_url&&!data.subscribers.next_page_url" @click="page++;load()">{{ $t('Next') }}</button></div></template></section></template>
