<script setup lang="ts">
import {t} from "../i18n"
import {ref,watch,computed} from 'vue'
import {useQuasar} from 'quasar'
import {api,send,ApiError} from '../api'
import {useCms} from '../store'
import Icon from './Icon.vue'
import MenuItemsEditor,{type MenuItem} from './MenuItemsEditor.vue'
const languageOptions=computed(()=>[{label:'English',value:'en'},{label:'دری',value:'fa'},{label:'پښتو',value:'ps'},{label:'العربية',value:'ar'}].filter(l=>cms.selected?.languages.includes(l.value)))
const newKey=()=>crypto.randomUUID()
const cms=useCms(),q=useQuasar(),location=ref('header'),language=ref('en'),name=ref('Main navigation'),items=ref<MenuItem[]>([]),menus=ref<any[]>([]),version=ref(0),saving=ref(false),loading=ref(false),error=ref(''),baseline=ref('')
const mark=()=>JSON.stringify({name:name.value,items:items.value}),dirty=computed(()=>mark()!==baseline.value)
function normalize(list:any[]):MenuItem[]{return list.map(i=>({key:i.key||crypto.randomUUID(),label:i.label,url:i.url,new_tab:!!i.new_tab,children:normalize(i.children||[])}))}
function select(){const m=menus.value.find(m=>m.location===location.value&&m.language===language.value);name.value=m?.name||location.value.charAt(0).toUpperCase()+location.value.slice(1)+' navigation';items.value=normalize(m?.items||[]);version.value=m?.version||0;baseline.value=mark()}
async function load(){if(!cms.selectedId)return;loading.value=true;error.value='';try{menus.value=await api('/websites/'+cms.selectedId+'/menus');select()}catch(e:any){error.value=e.message}finally{loading.value=false}}
function switchTo(kind:'location'|'language',value:string){const apply=()=>{if(kind==='location')location.value=value;else language.value=value;select()};if(dirty.value)q.dialog({title:t('Discard unsaved navigation changes?'),message:t('Save this menu first if you want to keep your edits.'),cancel:true}).onOk(apply);else apply()}
async function save(){saving.value=true;try{const saved=await api('/websites/'+cms.selectedId+'/menus',send('POST',{name:name.value,location:location.value,language:language.value,version:version.value,items:items.value}));version.value=saved.version;baseline.value=mark();const idx=menus.value.findIndex(m=>m.location===location.value&&m.language===language.value);if(idx<0)menus.value.push(saved);else menus.value[idx]=saved;q.notify({type:'positive',message:t('Navigation saved. The matching language and location now use this menu.')})}catch(e:any){q.notify({type:'negative',message:t(e.message)});if((e as ApiError).status===409)error.value=e.message}finally{saving.value=false}}
watch(()=>cms.selectedId,()=>{language.value=cms.selected?.default_language||'en';load()},{immediate:true})
</script>
<template><q-linear-progress v-if="loading" indeterminate color="primary"/><div class="website-toolbar"><div class="filter-tabs"><button v-for="l in ['header','mobile','footer','secondary']" :class="{active:location===l}" @click="switchTo('location',l)">{{ $t(l) }}</button></div><q-select outlined dense :model-value="language" :options="$translatedOptions(languageOptions)" emit-value map-options :label="$t('Menu language')" style="min-width:170px" @update:model-value="switchTo('language',$event)"/></div><div v-if="error" class="info-note"><span>{{ error }} {{ $t("Export or copy unsaved links before reloading.") }}</span><button class="btn secondary" @click="load">{{ $t("Reload menus") }}</button></div><div class="menu-layout"><section class="panel"><q-input outlined v-model="name" :label="$t('Menu name')" maxlength="120"/><MenuItemsEditor v-model="items"/><div v-if="!items.length" class="empty-state"><Icon name="Menu" :size="30"/><h3>{{ $t("A clear way around.") }}</h3><p>{{ $t("Add your first link for this language and location.") }}</p></div><div class="dialog-footer"><button class="btn secondary" @click="items.push({key:newKey(),label:'New link',url:'home',new_tab:false,children:[]})"><Icon name="Plus" :size="16"/>{{ $t("Add link") }}</button><q-btn color="primary" unelevated :label="$t('Save navigation')" :loading="saving" @click="save"/></div></section><aside class="panel"><Icon name="Route" :size="30"/><h3>{{ $t("Navigation that grows with you.") }}</h3><p class="muted">{{ $t("Drag links to reorder. Use each link’s menu to add children, indent, move up a level, or open in a new tab. Up to three levels and 100 links are supported.") }}</p><div class="info-note">{{ $t("Each language has its own menu. Mobile navigation falls back to that language’s header menu when no mobile menu exists.") }}</div><span class="status-pill" :class="dirty?'draft':'published'">{{ $t(dirty?'Unsaved changes':'All changes saved') }}</span></aside></div></template>
