<script setup lang="ts">
import{ref,inject}from'vue'
import{api,send}from'../api'
import{t}from'../i18n'
const props=defineProps<{kind:string;disabled?:boolean}>(),site=inject<string>('publicSite',''),language=inject<any>('publicLanguage',ref('en'))
const name=ref(''),email=ref(''),message=ref(''),company=ref(''),consent=ref(false),busy=ref(false),feedback=ref(''),error=ref(false)
async function submit(){if(props.disabled||!site)return;busy.value=true;feedback.value='';try{const response=await api<any>('/public/websites/'+site+'/'+(props.kind==='Contact'?'contact':'newsletter'),send('POST',{name:name.value,email:email.value,message:message.value,company:company.value,consent:consent.value,language:language.value||'en'}));feedback.value=response.message;error.value=false;message.value='';consent.value=false}catch(e:any){feedback.value=e.message;error.value=true}finally{busy.value=false}}
</script>
<template><form class="public-form" @submit.prevent="submit" @click.stop><label v-if="kind==='Contact'">{{ $t('Name') }}<input v-model="name" required maxlength="120" autocomplete="name" :disabled="disabled"/></label><label>{{ $t('Email address') }}<input type="email" v-model="email" required maxlength="254" autocomplete="email" :disabled="disabled"/></label><label v-if="kind==='Contact'">{{ $t('Message') }}<textarea v-model="message" required minlength="10" maxlength="10000" rows="5" :disabled="disabled"/></label><label class="honeypot" aria-hidden="true">Company<input v-model="company" tabindex="-1" autocomplete="off"/></label><label class="consent"><input type="checkbox" v-model="consent" required :disabled="disabled"/>{{ $t(kind==='Contact'?'I agree to be contacted about this message.':'I agree to receive newsletter emails. I can unsubscribe at any time.') }}</label><button class="public-button" :disabled="busy||disabled" type="submit">{{ $t(busy?'Sending…':kind==='Contact'?'Send message':'Subscribe') }}</button><small v-if="disabled">{{ $t('Forms are disabled in the editor preview.') }}</small><p v-if="feedback" role="status" :class="{danger:error}">{{ $t(feedback) }}</p></form></template>
