<script setup lang="ts">
import{ref,computed,onMounted}from'vue'
import{api,send}from'../api'
import{t,appLocale}from'../i18n'
const props=defineProps<{site:string}>(),products=ref<any[]>([]),cart=ref<Record<number,number>>({}),currency=ref('USD'),error=ref(''),busy=ref(false),receipt=ref<any>(null),page=ref(1),more=ref(false),key=ref(crypto.randomUUID()),form=ref({name:'',email:'',phone:'',address:'',consent:false})
const lines=computed(()=>products.value.filter(p=>cart.value[p.id]).map(p=>({...p,quantity:cart.value[p.id]}))),total=computed(()=>lines.value.reduce((s,p)=>s+p.price_minor*p.quantity,0))
const money=(n:number)=>new Intl.NumberFormat(appLocale.value,{style:'currency',currency:currency.value}).format(n/100)
async function load(){try{const d=await api<any>(`/public/websites/${props.site}/store/catalog?page=${page.value}`);products.value.push(...d.products.data);currency.value=d.currency;more.value=!!d.products.next_page_url}catch(e:any){error.value=e.message}}
onMounted(load)
function renewKey(){key.value=crypto.randomUUID()}
function add(p:any){if(p.stock>(cart.value[p.id]||0)&& (cart.value[p.id]||0)<99){cart.value[p.id]=(cart.value[p.id]||0)+1;key.value=crypto.randomUUID()}}
async function checkout(){busy.value=true;error.value='';try{receipt.value=await api(`/public/websites/${props.site}/store/checkout`,send('POST',{...form.value,idempotency_key:key.value,items:lines.value.map(p=>({product_id:p.id,quantity:p.quantity}))}));cart.value={};products.value=[];page.value=1;await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
</script>
<template><section class="storefront"><h2>{{ $t('Shop') }}</h2><p>{{ $t('Cash on delivery. No online payment is collected. Prices include all charges; delivery is free.') }}</p><p v-if="error" role="alert">{{ $t(error) }}</p><div v-if="receipt" class="info-note" role="status"><h3>{{ $t('Order received') }}</h3><p>{{ $t('Keep this reference for your records.') }}</p><strong>{{ receipt.reference }}</strong><p>{{ money(receipt.total_minor) }}</p><button class="btn secondary" @click="receipt=null;renewKey()">{{ $t('Continue shopping') }}</button></div><div class="store-grid"><article v-for="p in products" :key="p.id"><img v-if="p.image" :src="p.image" :alt="p.name" loading="lazy"/><h3>{{ p.name }}</h3><p>{{ p.description }}</p><strong>{{ money(p.price_minor) }}</strong><button class="public-button" :disabled="!p.stock||busy||!!receipt" @click="add(p)">{{ $t(p.stock?'Add to cart':'Out of stock') }}</button></article></div><button v-if="more" class="btn secondary" @click="page++;load()">{{ $t('Load more') }}</button><p v-if="!products.length">{{ $t('No products available.') }}</p><form v-if="lines.length&&!receipt" class="public-form checkout-form" @submit.prevent="checkout" @input="renewKey()"><h3>{{ $t('Your cart') }}</h3><div v-for="p in lines" :key="p.id" class="action-row"><span>{{ p.name }} × {{ p.quantity }} · {{ money(p.price_minor*p.quantity) }}</span><button type="button" class="text-link danger" :disabled="busy" @click="delete cart[p.id];renewKey()">{{ $t('Remove') }}</button></div><strong>{{ $t('Total') }}: {{ money(total) }}</strong><label>{{ $t('Name') }}<input v-model="form.name" required maxlength="120" autocomplete="name" :disabled="busy"/></label><label>{{ $t('Email address') }}<input v-model="form.email" type="email" required maxlength="254" autocomplete="email" :disabled="busy"/></label><label>{{ $t('Phone') }}<input v-model="form.phone" type="tel" required maxlength="40" autocomplete="tel" :disabled="busy"/></label><label>{{ $t('Delivery address') }}<textarea v-model="form.address" required minlength="10" maxlength="2000" autocomplete="street-address" :disabled="busy"/></label><label class="consent"><input v-model="form.consent" type="checkbox" required :disabled="busy"/>{{ $t('I agree to be contacted to fulfill this order and to pay on delivery.') }}</label><button class="public-button" type="submit" :disabled="busy">{{ $t(busy?'Submitting…':'Place order · Cash on delivery') }}</button></form></section></template>
