<script setup lang="ts">
import {t} from "../i18n"
import { ref, watch } from 'vue'
import { useQuasar } from 'quasar'
import { api, send } from '../api'
import { useCms } from '../store'
import Icon from './Icon.vue'
const props=defineProps<{siteId:number}>(),cms=useCms(),q=useQuasar()
const data=ref<any>({members:[],roles:[]}),error=ref(''),saving=ref(false),dialog=ref(false),form=ref<any>({email:'',role_id:null})
async function load(){error.value='';try{data.value=await api('/websites/'+props.siteId+'/members')}catch(e:any){error.value=e.message}}
function edit(member?:any){form.value=member?{email:member.email,role_id:member.role_id}:{email:'',role_id:data.value.roles.find((r:any)=>r.name==='Editor')?.id};dialog.value=true}
async function save(){saving.value=true;try{await api('/websites/'+props.siteId+'/members',send('POST',form.value));dialog.value=false;await load();q.notify({type:'positive',message:t('Website access updated.')})}catch(e:any){q.notify({type:'negative',message:t(e.message)})}finally{saving.value=false}}
function remove(member:any){q.dialog({title:t('Remove '+member.name+' from this website?'),message:t('Their account and memberships on other websites will remain unchanged.'),cancel:true}).onOk(async()=>{try{await api('/websites/'+props.siteId+'/members/'+member.id,{method:'DELETE'});await load()}catch(e:any){q.notify({type:'negative',message:t(e.message)})}})}
watch(()=>props.siteId,load,{immediate:true})
</script>
<template><div v-if="error" class="empty-state"><Icon name="LockKeyhole" :size="30"/><h2>{{ $t("Team access is restricted") }}</h2><p>{{ error }}</p></div><div v-else><div class="website-toolbar"><p class="muted">{{ $t("People with access to this website. Workspace Super Admins have access to every website.") }}</p><button class="btn primary" @click="edit()"><Icon name="Plus" :size="16"/>{{ $t("Add member") }}</button></div><div class="table-panel"><table class="cms-table"><thead><tr><th>{{ $t("Team member") }}</th><th>{{ $t("Website role") }}</th><th>{{ $t("Account") }}</th><th></th></tr></thead><tbody><tr v-for="m in data.members" :key="m.id"><td><div class="person-cell"><span class="avatar">{{ m.name.charAt(0) }}</span><div><strong>{{ m.name }}</strong><small>{{ m.email }}</small></div></div></td><td>{{ $t(data.roles.find((r:any)=>r.id===m.role_id)?.name) }}</td><td><span :class="['status-pill',m.is_active?'published':'archived']">{{ $t(m.is_active?'Active':'Suspended') }}</span></td><td><div class="table-actions"><button class="text-link" @click="edit(m)">{{ $t("Change role") }}</button><button class="icon-btn danger" @click="remove(m)" :disabled="m.id===cms.user.id" :aria-label="$t('Remove membership')"><Icon name="Trash2" :size="16"/></button></div></td></tr></tbody></table><p v-if="!data.members.length" class="empty-text">{{ $t("No direct memberships yet. Add an existing account to your team.") }}</p></div></div><q-dialog v-model="dialog"><q-card class="standard-dialog"><h2>{{ $t("A place on your team.") }}</h2><p>{{ $t("Add an existing active account by email. A workspace Super Admin can create accounts in Users & roles.") }}</p><form @submit.prevent="save"><q-input outlined v-model="form.email" :label="$t('Account email')" type="email" required/><q-select outlined v-model="form.role_id" :options="$translatedOptions(data.roles.map((r:any)=>({label:r.name,value:r.id})))" emit-value map-options :label="$t('Website role')"/><div class="dialog-footer"><button class="btn secondary" type="button" @click="dialog=false">{{ $t("Cancel") }}</button><q-btn color="primary" unelevated :label="$t('Save membership')" type="submit" :loading="saving"/></div></form></q-card></q-dialog></template>
