<script setup lang="ts">
import {t} from "../i18n"
import { ref, reactive, watch } from 'vue'
import { useQuasar } from 'quasar'
import { api, send } from '../api'
import { useCms } from '../store'
import Icon from './Icon.vue'
const props=defineProps<{modelValue:boolean}>(), emit=defineEmits(['update:modelValue','created']), cms=useCms(), q=useQuasar()
const step=ref(1), saving=ref(false)
const form=reactive({name:'',domain:'',description:'',type:'Business',default_language:'en',languages:['en','fa','ps','ar'],default_currency:'USD',currencies:['USD','AFN','EUR','GBP','AED','SAR','PKR'],theme:'Evergreen'})
const languages=[{label:'English',value:'en'},{label:'Dari / فارسی',value:'fa'},{label:'Pashto / پښتو',value:'ps'},{label:'Arabic / العربية',value:'ar'}]
const types=[['Business','BriefcaseBusiness'],['Corporate','Building2'],['University','GraduationCap'],['School','School'],['E-commerce','ShoppingBag'],['Blog','NotebookPen'],['Portfolio','Image'],['News','Newspaper'],['Agency','Sparkles'],['Landing Page','PanelTop'],['Custom','Blocks']]
watch(()=>props.modelValue,v=>{if(v){step.value=1;form.name='';form.domain='';form.description=''}})
function next(){if(step.value===1&&(!form.name.trim()||!form.domain.match(/^[a-z0-9.-]+$/i))){q.notify({type:'warning',message:t('Add a name and domain without https:// to continue.')});return}step.value++}
async function create(){saving.value=true;try{const s=await api('/websites',send('POST',form));await cms.load();emit('update:modelValue',false);emit('created',s.id);q.notify({type:'positive',message:t('Your website is ready. Let’s make it yours.')})}catch(e:any){q.notify({type:'negative',message:t(e.message)})}finally{saving.value=false}}
</script>
<template><q-dialog :model-value="modelValue" @update:model-value="emit('update:modelValue',$event)" persistent><q-card class="wizard-dialog"><div class="dialog-heading"><span class="brand-mark"><Icon name="Sparkles"/></span><div><span class="eyebrow">{{ $t("SOMETHING GREAT STARTS HERE") }}</span><h2>{{ $t("Create your website") }}</h2></div><button class="icon-btn" @click="emit('update:modelValue',false)" :aria-label="$t('Close')"><Icon name="X"/></button></div><div class="wizard-progress"><span v-for="(s,i) in ['The basics','Website type','Languages','Currencies','Your theme']" :class="{current:step===i+1,done:step>i+1}"><i>{{ step>i+1?'✓':i+1 }}</i>{{ $t(s) }}</span></div><div class="wizard-body">
<template v-if="step===1"><h3>{{ $t("Let’s give your idea a home.") }}</h3><p>{{ $t("You can change all of this later.") }}</p><q-input outlined v-model="form.name" :label="$t('Website name')" :placeholder="$t('e.g. Evergreen Studio')" maxlength="120"/><q-input outlined v-model="form.domain" :label="$t('Domain')" :placeholder="$t('e.g. evergreen.studio')" hint="Enter a domain without https://. DNS is configured separately."/><q-input outlined v-model="form.description" :label="$t('A little about your website')" type="textarea" rows="3" maxlength="2000"/></template>
<template v-if="step===2"><h3>{{ $t("What are you bringing to life?") }}</h3><p>{{ $t("Choose the closest fit. Every type includes the full core toolkit.") }}</p><div class="type-grid"><button v-for="[name,icon] in types" :class="{selected:form.type===name}" @click="form.type=name"><Icon :name="icon" :size="23"/><strong>{{ name }}</strong><Icon v-if="form.type===name" name="CircleCheck" :size="16"/></button></div></template>
<template v-if="step===3"><h3>{{ $t("A website that speaks your language.") }}</h3><p>{{ $t("English, Dari, Pashto, and Arabic are included automatically, with RTL layouts.") }}</p><q-select outlined v-model="form.default_language" :options="$translatedOptions(languages)" emit-value map-options :label="$t('Default language')"/><div class="included-row" v-for="lang in languages"><Icon name="CircleCheck" :size="19"/><strong>{{ $t(lang.label) }}</strong><span>{{ $t(lang.value==='en'?'Left to right':'Right to left') }}</span></div></template>
<template v-if="step===4"><h3>{{ $t("Think beyond borders.") }}</h3><p>{{ $t("Set your base currency. Manual exchange rates can be configured in your website.") }}</p><q-select emit-value map-options outlined v-model="form.default_currency" :options="$translatedOptions(['USD','AFN','EUR','GBP','AED','SAR','PKR'])" :label="$t('Default currency')"/><div class="info-note"><Icon name="CircleDollarSign"/><span>{{ $t("All seven currencies are enabled. Exchange rates start at 1 and must be configured before using financial content.") }}</span></div></template>
<template v-if="step===5"><h3>{{ $t("Make a great first impression.") }}</h3><p>{{ $t("A full theme, appearance settings, and starter page are included from day one.") }}</p><div class="theme-grid"><button v-for="(color,name) in {Evergreen:'#286b54',Editorial:'#855039',Studio:'#62588b',Scholar:'#274e75'}" :class="{selected:form.theme===name}" @click="form.theme=String(name)"><div class="theme-swatch" :style="{background:color}"><span></span><i></i><i></i></div><strong>{{ name }}</strong><Icon v-if="form.theme===name" name="CircleCheck" :size="17"/></button></div><div class="info-note"><Icon name="PackageCheck"/><span>{{ $t("Ready to create: theme, header, footer, navigation, visual builder, starter template, media library, 4 languages, currencies, and SEO settings.") }}</span></div></template>
</div><div class="dialog-footer"><button class="btn secondary" @click="step===1?emit('update:modelValue',false):step--">{{ $t(step===1?'Cancel':'Back') }}</button><span>{{ $t("Step") }} {{ step }} {{ $t("of 5") }}</span><button v-if="step<5" class="btn primary" @click="next">{{ $t("Continue") }} <Icon name="ArrowRight" :size="16"/></button><q-btn v-else unelevated color="primary" :label="$t('Create website')" :loading="saving" @click="create"/></div></q-card></q-dialog></template>
