<script setup lang="ts">
import {t} from "../i18n"
const clone = <T,>(value:T):T => JSON.parse(JSON.stringify(value))
import { ref, watch, computed, reactive } from 'vue'
import { useQuasar } from 'quasar'
import { useCms } from '../store'
import { api, send } from '../api'
import type { Page } from '../types'
import Icon from './Icon.vue'
import MediaLibrary from './MediaLibrary.vue'
import Appearance from './Appearance.vue'
import PageBuilder from './PageBuilder.vue'
import TeamManagement from './TeamManagement.vue'
import GlobalComponents from './GlobalComponents.vue'
import Commerce from './Commerce.vue'
import Inbox from './Inbox.vue'
import MenuBuilder from './MenuBuilder.vue'
import draggable from 'vuedraggable'
const props=defineProps<{view:string}>(),emit=defineEmits(['navigate','create']),cms=useCms(),q=useQuasar()
const pages=ref<Page[]>([]),search=ref(''),status=ref('All pages'),editing=ref<Page|null>(null),resources=ref<any[]>([]),loading=ref(false),newPage=ref(false),saving=ref(false),menuItems=ref<any[]>([]),translation=reactive({key:'',language:'fa',value:''}),pageForm=reactive({title:'',slug:'',language:'en'}),settings=reactive<Record<string,any>>({}),currency=reactive({currency_code:'USD',exchange_rate:1,position:'before'}),currencyDialog=ref(false),templateDialog=ref(false),chosenTemplate=ref<any>(null)
const tabs=['Pages','Theme & Appearance','Global components','Media library','Menus','Templates','Languages','Currencies','Team','Inbox','Products','Orders','Settings']
const descriptions:Record<string,string>={'Pages':'Your story, one beautiful page at a time.','Theme & Appearance':'One visual identity. Every page, beautifully connected.','Media library':'A home for your photos, files, and everyday inspiration.','Templates':'Good ideas are worth using again.','Languages':'Different languages. The same thoughtful experience.','Currencies':'A local experience for a global audience.','Menus':'Help your visitors find their way.','Settings':'All the little details that make this website yours.','Global components':'Your header, footer, announcement and call to action. Shared everywhere.','Team':'The right people, with the right permissions.','Activity log':'A clear picture of what’s happening in your workspace.'}
const filteredPages=computed(()=>pages.value.filter(p=>(p.title+' '+p.slug).toLowerCase().includes(search.value.toLowerCase())&&(status.value==='All pages'||p.status===status.value.toLowerCase())))
const languages=[{code:'en',name:'English',native:'English',dir:'LTR'},{code:'fa',name:'Dari / Farsi',native:'دری / فارسی',dir:'RTL'},{code:'ps',name:'Pashto',native:'پښتو',dir:'RTL'},{code:'ar',name:'Arabic',native:'العربية',dir:'RTL'}]
async function load(){if(!cms.selectedId)return;loading.value=true;search.value='';try{Object.assign(settings,cms.selected);pages.value=await api('/websites/'+cms.selectedId+'/pages');const type=({'Templates':'templates','Languages':'translations','Currencies':'currencies'} as Record<string,string>)[props.view];resources.value=type?await api('/websites/'+cms.selectedId+'/'+type):[];if(type==='menus')menuItems.value=clone(resources.value.find(m=>m.location==='header')?.items||[])}catch(e:any){q.notify({type:'negative',message:t(e.message)})}finally{loading.value=false}}
watch([()=>cms.selectedId,()=>props.view],()=>{editing.value=null;load()},{immediate:true})
async function createPage(){if(!pageForm.title.trim())return;saving.value=true;try{const title=pageForm.title,slug=pageForm.slug||title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const p=await api<Page>('/websites/'+cms.selectedId+'/pages',send('POST',{title,slug,language:pageForm.language,status:'draft',seo:{},blocks:chosenTemplate.value?.blocks||[{id:crypto.randomUUID(),type:'Hero',title:'A new idea starts here.',text:'Make this page your own.',image:cms.selected?.image,button:'Discover more'}]}));newPage.value=false;templateDialog.value=false;chosenTemplate.value=null;pageForm.title='';pageForm.slug='';await load();await cms.load();editing.value=p}catch(e:any){q.notify({type:'negative',message:t(e.message)})}finally{saving.value=false}}
function deletePage(p:Page){q.dialog({title:t('Delete “'+p.title+'”?'),message:t('This permanently deletes the page and its revision history.'),cancel:true,persistent:true}).onOk(async()=>{try{await api('/websites/'+cms.selectedId+'/pages/'+p.id,{method:'DELETE'});await load();await cms.load();q.notify({type:'positive',message:t('Page deleted.')})}catch(e:any){q.notify({type:'negative',message:t(e.message)})}})}
async function saveSettings(){saving.value=true;try{await api('/websites/'+cms.selectedId,send('PUT',{name:settings.name,domain:settings.domain,description:settings.description,status:settings.status,default_language:settings.default_language,default_currency:settings.default_currency}));await cms.load();q.notify({type:'positive',message:t('Website settings saved.')})}catch(e:any){q.notify({type:'negative',message:t(e.message)})}finally{saving.value=false}}
async function saveResource(kind:string,data:any){try{await api('/websites/'+cms.selectedId+'/'+kind,send('POST',data));await load();q.notify({type:'positive',message:t('Changes saved.')});currencyDialog.value=false}catch(e:any){q.notify({type:'negative',message:t(e.message)})}}
async function translatePage(p:Page){q.dialog({title:t('Create an independent translation'),message:t('Choose a target language: en, fa, ps, or ar.'),prompt:{model:'fa',type:'text'},cancel:true}).onOk(async(lang:string)=>{if(!languages.some(l=>l.code===lang)){q.notify({type:'warning',message:t('Choose en, fa, ps, or ar.')});return}try{const translated=await api<Page>('/websites/'+cms.selectedId+'/pages',send('POST',{title:p.title,slug:p.slug,language:lang,status:'draft',blocks:p.blocks,seo:p.seo}));editing.value=translated;await load();q.notify({type:'positive',message:t('Independent draft created. Edit the text in the target language.')})}catch(e:any){q.notify({type:'negative',message:t(e.message)})}})}
</script>
<template><PageBuilder v-if="editing" :key="editing.id" :page="editing" @close="editing=null;load()" @saved="load"/><div v-else class="page-wrap workspace-page"><div class="website-context"><span class="site-letter" :style="{background:(cms.selected?.color||'#286b54')+'15',color:cms.selected?.color}"><Icon name="Globe2"/></span><q-select borderless dense v-model="cms.selectedId" :options="cms.websites.map(s=>({label:s.name,value:s.id}))" emit-value map-options/><span :class="['status-pill',cms.selected?.status]"><i></i>{{ $t(cms.selected?.status) }}</span><a v-if="cms.selected" :href="'/site/'+cms.selectedId+'/home'" target="_blank" class="text-link">{{ $t("Visit website") }} <Icon name="ArrowUpRight" :size="16"/></a></div><div class="page-heading"><div><span class="eyebrow">{{ $t(cms.selected?.name || 'YOUR WORKSPACE') }}</span><h1>{{ $t(view) }}</h1><p>{{ $t(descriptions[view]) }}</p></div><button v-if="view==='Pages'" class="btn primary" @click="newPage=true;chosenTemplate=null"><Icon name="Plus" :size="18"/>{{ $t("Create page") }}</button></div><div class="site-tabs" v-if="view!=='Activity log'"><button v-for="tab in tabs" :class="{active:view===tab}" @click="emit('navigate',tab)">{{ $t(tab==='Media library'?'Media':tab==='Theme & Appearance'?'Appearance':tab) }}</button></div><div v-if="!cms.selected" class="empty-state"><h2>{{ $t("Your workspace is ready for an idea.") }}</h2><button class="btn primary" @click="emit('create')">{{ $t("Create your first website") }}</button></div><template v-else><q-linear-progress v-if="loading" indeterminate color="primary"/>
<template v-if="view==='Pages'"><div class="website-toolbar"><div class="filter-tabs"><button v-for="s in ['All pages','Published','Draft','Scheduled','Archived']" :class="{active:status===s}" @click="status=s">{{ $t(s) }}</button></div><div class="inline-search"><Icon name="Search" :size="16"/><input v-model="search" :placeholder="$t('Search pages…')"></div></div><div class="table-panel"><table class="cms-table"><thead><tr><th>{{ $t("Page title") }}</th><th>{{ $t("Status") }}</th><th>{{ $t("Language") }}</th><th>{{ $t("Last updated") }}</th><th></th></tr></thead><tbody><tr v-for="p in filteredPages" :key="p.id"><td><button class="page-name" @click="editing=clone(p)"><span class="page-icon"><Icon name="FileText" :size="19"/></span><span><strong>{{ p.title }}</strong><small>/{{ p.slug }}</small></span></button></td><td><span :class="['status-pill',p.status]"><i></i>{{ $t(p.status) }}</span></td><td><span class="language-badge">{{ p.language.toUpperCase() }}</span></td><td class="muted">{{ new Date(p.updated_at).toLocaleDateString('en',{month:'short',day:'numeric',year:'numeric'}) }}</td><td><div class="table-actions"><button class="text-link" @click="editing=clone(p)">{{ $t("Edit page") }} <Icon name="ArrowRight" :size="15"/></button><q-btn flat round dense :aria-label="$t('Page actions')"><Icon name="Ellipsis"/><q-menu><q-list style="min-width:170px"><q-item clickable v-close-popup @click="translatePage(p)"><q-item-section>{{ $t("Create translation") }}</q-item-section></q-item><q-item clickable v-close-popup @click="deletePage(p)"><q-item-section class="text-negative">{{ $t("Delete page") }}</q-item-section></q-item></q-list></q-menu></q-btn></div></td></tr></tbody></table><div v-if="!filteredPages.length" class="empty-state"><Icon name="FilePlus2" :size="30"/><h3>{{ $t("A blank page. A new possibility.") }}</h3><p>{{ $t("Create a page or change your search filters.") }}</p></div><div class="table-footer">{{ filteredPages.length }} {{ $t("pages") }} <span>{{ $t("Content is saved independently for each language.") }}</span></div></div></template>
<GlobalComponents v-else-if="view==='Global components'"/><TeamManagement v-else-if="view==='Team'" :site-id="cms.selectedId!"/><Appearance v-else-if="view==='Theme & Appearance'"/>
<MediaLibrary v-else-if="view==='Media library'" :site-id="cms.selectedId!"/>
<template v-else-if="view==='Templates'"><div class="info-note"><Icon name="BookmarkCheck"/><span>{{ $t("Save any page as a template from the visual builder. Reuse the layout without changing the original.") }}</span></div><div class="template-grid"><article v-for="t in resources" class="panel template-card"><div class="template-art"><Icon name="PanelsTopLeft" :size="48"/><span>{{ t.blocks.length }} {{ $t("thoughtfully arranged blocks") }}</span></div><h3>{{ t.name }}</h3><p>{{ $t(t.type) }} {{ $t("template ·") }} {{ cms.selected?.name }}</p><button class="btn secondary" @click="chosenTemplate=t;newPage=true">{{ $t("Use template") }} <Icon name="ArrowRight" :size="15"/></button></article></div></template>
<template v-else-if="view==='Languages'"><div class="language-grid"><article v-for="l in languages" class="panel language-card"><span class="language-code">{{ l.code.toUpperCase() }}</span><div><h3>{{ $t(l.name) }}</h3><p>{{ l.native }}</p></div><span class="direction-badge">{{ l.dir }}</span><span v-if="cms.selected?.default_language===l.code" class="status-pill published">{{ $t("Default") }}</span><small>{{ pages.filter(p=>p.language===l.code).length }} {{ $t("pages") }}</small></article></div><div class="panel translation-panel"><h2>{{ $t("Independent content, every language.") }}</h2><p class="muted">{{ $t("Use “Create translation” in a page’s menu to create and edit a separate language version. Shared component text can be translated with keys such as components.Header.title or components.Footer.text.") }}</p><form class="translation-form" @submit.prevent="saveResource('translations',translation)"><q-input outlined v-model="translation.key" :label="$t('Translation key')" :placeholder="$t('navigation.home')" required/><q-select outlined v-model="translation.language" :options="$translatedOptions(languages.map(l=>({label:l.name,value:l.code})))" emit-value map-options :label="$t('Language')"/><q-input outlined v-model="translation.value" :label="$t('Translated content')" :input-style="{direction:translation.language==='en'?'ltr':'rtl'}" required/><button class="btn primary" type="submit">{{ $t("Save translation") }}</button></form><table class="cms-table"><thead><tr><th>{{ $t("Key") }}</th><th>{{ $t("Language") }}</th><th>{{ $t("Translation") }}</th></tr></thead><tbody><tr v-for="t in resources"><td><code>{{ t.key }}</code></td><td>{{ t.language }}</td><td :dir="t.language==='en'?'ltr':'rtl'">{{ t.value }}</td></tr></tbody></table><p class="empty-text" v-if="!resources.length">{{ $t("No translation keys yet. Add your first above.") }}</p></div></template>
<template v-else-if="view==='Currencies'"><div class="info-note"><Icon name="Info"/><span>{{ $t("Rates are managed manually and are relative to") }} {{ cms.selected?.default_currency }}{{ $t(". Store orders use the website base currency. Exchange rates are for display only.") }}</span></div><div class="table-panel"><table class="cms-table"><thead><tr><th>{{ $t("Currency") }}</th><th>{{ $t("Exchange rate") }}</th><th>{{ $t("Symbol position") }}</th><th>{{ $t("Rate source") }}</th><th></th></tr></thead><tbody><tr v-for="c in resources"><td><strong>{{ c.currency_code }}</strong><span v-if="c.currency_code===cms.selected?.default_currency" class="default-label">{{ $t("Default") }}</span></td><td>{{ Number(c.exchange_rate).toFixed(4) }}</td><td>{{ $t(c.position) }}</td><td><span class="language-badge">{{ $t("Manual") }}</span></td><td><button class="text-link" @click="Object.assign(currency,c);currencyDialog=true">{{ $t("Configure") }} <Icon name="ArrowRight" :size="15"/></button></td></tr></tbody></table></div></template>
<Inbox v-else-if="view==='Inbox'"/><Commerce v-else-if="view==='Products'||view==='Orders'" :orders="view==='Orders'"/><MenuBuilder v-else-if="view==='Menus'"/>
<template v-else-if="view==='Settings'"><form class="settings-layout" @submit.prevent="saveSettings"><section class="panel"><h2>{{ $t("The essentials") }}</h2><p class="muted">{{ $t("A little information goes a long way.") }}</p><q-input outlined v-model="settings.name" :label="$t('Website name')" required/><q-input outlined v-model="settings.domain" :label="$t('Domain')" required/><q-input outlined v-model="settings.description" :label="$t('Description / tagline')" type="textarea" rows="3"/><div class="form-two"><q-select outlined v-model="settings.default_language" :options="$translatedOptions(languages.map(l=>({label:l.name,value:l.code})))" emit-value map-options :label="$t('Default language')"/><q-select emit-value map-options outlined v-model="settings.default_currency" :options="$translatedOptions(['USD','AFN','EUR','GBP','AED','SAR','PKR'])" :label="$t('Default currency')"/></div><q-btn unelevated color="primary" :label="$t('Save settings')" type="submit" :loading="saving"/></section><aside class="panel"><Icon name="Radio" :size="26"/><h2>{{ $t("Ready for the world?") }}</h2><p class="muted">{{ $t("Published websites expose their published pages. Draft websites stay private.") }}</p><q-select emit-value map-options outlined v-model="settings.status" :options="$translatedOptions(['draft','published','archived'])" :label="$t('Website status')"/><div class="info-note">{{ $t("Your domain is a configuration value. Pointing a custom domain to this installation requires DNS and web-server setup.") }}</div></aside></form></template>
<template v-else-if="view==='Activity log'"><div class="panel"><div v-for="a in cms.activity" class="activity-row"><span class="activity-icon"><Icon name="History" :size="18"/></span><div><p><strong>{{ a.user||'System' }}</strong> {{ $t(a.action) }} <strong>{{ a.subject }}</strong></p><small>{{ new Date(a.created_at).toLocaleString() }} · {{ cms.websites.find(s=>s.id===a.website_id)?.name }}</small></div></div></div></template>
</template></div>
<q-dialog v-model="newPage"><q-card class="standard-dialog"><span class="eyebrow">{{ $t("A FRESH START") }}</span><h2>{{ $t(chosenTemplate?'Make this template your own.':'Your next great page.') }}</h2><form @submit.prevent="createPage"><q-input outlined v-model="pageForm.title" :label="$t('Page title')" autofocus required/><q-input outlined v-model="pageForm.slug" :label="$t('URL slug (optional)')" hint="Generated from your title if left blank."/><q-select outlined v-model="pageForm.language" :options="$translatedOptions(languages.map(l=>({label:l.name,value:l.code})))" emit-value map-options :label="$t('Content language')"/><div class="dialog-footer"><button class="btn secondary" type="button" @click="newPage=false">{{ $t("Cancel") }}</button><q-btn unelevated color="primary" :label="$t('Open page builder')" :loading="saving" type="submit"/></div></form></q-card></q-dialog><q-dialog v-model="currencyDialog"><q-card class="standard-dialog"><h2>{{ $t("Configure") }} {{ currency.currency_code }}</h2><q-input outlined v-model.number="currency.exchange_rate" type="number" min="0.00000001" step="0.00000001" :label="$t('Exchange rate')"/><q-select emit-value map-options outlined v-model="currency.position" :options="$translatedOptions(['before','after'])" :label="$t('Symbol position')"/><div class="dialog-footer"><button class="btn secondary" @click="currencyDialog=false">{{ $t("Cancel") }}</button><button class="btn primary" @click="saveResource('currencies',currency)">{{ $t("Save currency") }}</button></div></q-card></q-dialog></template>
