import{randomUUID,randomBytes,createHash}from'node:crypto';
const fail=(message,status=422)=>{throw Object.assign(new Error(message),{status})};
const hash=v=>createHash('sha256').update(v).digest('hex');
const email=v=>typeof v==='string'&&v.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const text=(v,min,max)=>typeof v==='string'&&v.trim().length>=min&&v.length<=max;
const paginate=(rows,page=1,size=30)=>{page=Math.max(1,parseInt(page)||1);return{data:rows.slice((page-1)*size,page*size),total:rows.length,current_page:page,next_page_url:rows.length>page*size?'?page='+(page+1):null}};
export function registerBusinessPublic(app,{all,one,insert,update,db}){
 const published=id=>{const w=one('websites',id);if(!w||w.status!=='published')fail('Website not found.',404);return w};
 const limits=new Map();const limit=(req,res,next)=>{const k=req.ip+req.path,n=limits.get(k)||{at:Date.now(),n:0};if(Date.now()-n.at>60000){n.n=0;n.at=Date.now()}if(++n.n>10)return res.status(429).json({message:'Too many requests. Try again later.'});limits.set(k,n);if(limits.size>10000)limits.clear();next()};
 app.post('/api/public/websites/:site/contact',limit,(req,res)=>{const id=+req.params.site;published(id);const d=req.body;if(!text(d.name,1,120)||!email(d.email)||!text(d.message,10,10000)||!d.consent||d.company||!['en','fa','ps','ar'].includes(d.language))fail('Enter your name, email, message and consent.');insert('submissions',id,{name:d.name,email:d.email,message:d.message,language:d.language,status:'new'});res.status(201).json({message:'Message received.'})});
 app.post('/api/public/websites/:site/newsletter',limit,(req,res)=>{const id=+req.params.site;published(id);const d=req.body;if(!email(d.email)||!d.consent||d.company||!['en','fa','ps','ar'].includes(d.language))fail('Enter a valid email and consent.');const e=d.email.toLowerCase(),token=randomBytes(32).toString('hex'),old=all('subscribers',id).find(s=>s.email===e),data={email:e,language:d.language,token_hash:hash(token),expires:Date.now()+86400000,consented_at:new Date().toISOString(),preview_email_url:`/site/${id}/home?newsletter=${token}&email=${encodeURIComponent(e)}`};if(old)update('subscribers',old.id,id,data);else insert('subscribers',id,{...data,status:'pending'});res.status(202).json({message:'Preview email available in admin inbox.'})});
 app.post('/api/public/websites/:site/subscription',limit,(req,res)=>{const id=+req.params.site;published(id);const d=req.body;if(!email(d.email)||!text(d.token,64,64)||!['confirm','unsubscribe'].includes(d.action))fail('Invalid subscription request.');const s=all('subscribers',id).find(s=>s.email===d.email.toLowerCase()&&s.token_hash===hash(d.token)&&s.expires>Date.now());if(!s)fail('This link is invalid or expired. Request a new email.');update('subscribers',s.id,id,{status:d.action==='confirm'?'subscribed':'unsubscribed',confirmed_at:d.action==='confirm'?new Date().toISOString():null,token_hash:null,preview_email_url:null});res.json({ok:true})});
 app.get('/api/public/websites/:site/store/catalog',(req,res)=>{const id=+req.params.site,w=published(id);res.json({currency:w.default_currency,products:paginate(all('products',id).filter(p=>p.active&&p.currency===w.default_currency).map(({id,name,description,image,price_minor,currency,stock})=>({id,name,description,image,price_minor,currency,stock})),req.query.page,24),payment_method:'cod'})});
 app.post('/api/public/websites/:site/store/checkout',limit,(req,res)=>{const id=+req.params.site,w=published(id),d=req.body;if(!/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(d.idempotency_key)||!text(d.name,1,120)||!email(d.email)||!text(d.phone,1,40)||!text(d.address,10,2000)||!d.consent||!Array.isArray(d.items)||d.items.length<1||d.items.length>50||new Set(d.items.map(i=>i.product_id)).size!==d.items.length)fail('Enter valid checkout details and products.');const fingerprint=hash(JSON.stringify(d));db.exec('BEGIN IMMEDIATE');try{const old=all('orders',id).find(o=>o.idempotency_key===d.idempotency_key);if(old){if(old.request_hash!==fingerprint)fail('Checkout key already used for different details.',409);db.exec('COMMIT');return res.json({reference:old.reference,total_minor:old.total_minor,currency:old.currency})}let total=0;const items=d.items.map(i=>{const p=one('products',i.product_id,id);if(!p||!p.active||p.currency!==w.default_currency||!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>99)fail('A product is unavailable.');if(p.stock<i.quantity)fail('Insufficient stock for '+p.name);total+=p.price_minor*i.quantity;update('products',p.id,id,{stock:p.stock-i.quantity,version:p.version+1});return{product_id:p.id,name:p.name,sku:p.sku,price_minor:p.price_minor,quantity:i.quantity}});const o=insert('orders',id,{reference:randomUUID(),idempotency_key:d.idempotency_key,request_hash:fingerprint,name:d.name,email:d.email,phone:d.phone,address:d.address,currency:w.default_currency,total_minor:total,items,status:'pending',payment_status:'unpaid',payment_method:'cod'});db.exec('COMMIT');res.status(201).json({reference:o.reference,total_minor:total,currency:o.currency})}catch(e){db.exec('ROLLBACK');throw e}});
}
export function registerBusinessAdmin(app,{all,one,insert,update,remove,log,db}){
 app.get('/api/websites/:site/inbox',(req,res)=>res.json({messages:paginate(all('submissions',req.siteId),req.query.messages_page),subscribers:paginate(all('subscribers',req.siteId).map(({token_hash,expires,...s})=>s),req.query.subscribers_page)}));
 app.put('/api/websites/:site/submissions/:submission',(req,res)=>{if(!['new','read','archived'].includes(req.body.status))fail('Invalid message status.');update('submissions',req.params.submission,req.siteId,{status:req.body.status});res.json({ok:true})});
 app.delete('/api/websites/:site/engagement/:kind/:entry',(req,res)=>{if(!['submissions','subscribers'].includes(req.params.kind))fail('Not found.',404);remove(req.params.kind,req.params.entry,req.siteId);res.json({ok:true})});
 app.get('/api/websites/:site/products',(req,res)=>res.json(paginate(all('products',req.siteId),req.query.page)));
 function save(req,res){const d=req.body,id=+req.params.product,w=one('websites',req.siteId);if(!text(d.name,1,190)||!text(d.sku,1,80)||d.description&&!text(d.description,0,10000)||d.image&&!/^(https?:\/\/[^\s]+|\/(?!\/)[^\s]+)$/.test(d.image)||d.currency!==w.default_currency||!Number.isInteger(d.price_minor)||d.price_minor<1||d.price_minor>100000000||!Number.isInteger(d.stock)||d.stock<0||d.stock>1000000||typeof d.active!=='boolean')fail('Enter valid product details.');if(all('products',req.siteId).some(p=>p.sku===d.sku&&p.id!==id))fail('SKU is already in use.');const old=id?one('products',id,req.siteId):null;if(id&&!old)fail('Product not found.',404);if(old&&old.version!==d.version)fail('Product changed. Reload before saving.',409);const data={name:d.name,sku:d.sku,description:d.description,image:d.image,currency:d.currency,price_minor:d.price_minor,stock:d.stock,active:d.active,version:(old?.version||0)+1};res.json(id?update('products',id,req.siteId,data):insert('products',req.siteId,data));log(req.siteId,'saved product',d.name)}
 app.post('/api/websites/:site/products',save);app.put('/api/websites/:site/products/:product',save);
 app.get('/api/websites/:site/orders',(req,res)=>res.json(paginate(all('orders',req.siteId).map(({idempotency_key,request_hash,...o})=>o),req.query.page)));
 app.put('/api/websites/:site/orders/:order',(req,res)=>{const o=one('orders',req.params.order,req.siteId),d=req.body;if(!o)fail('Order not found.',404);if(o.status!==d.expected_status||o.payment_status!==d.expected_payment_status)fail('Order changed. Reload before saving.',409);const allowed={pending:['pending','confirmed','cancelled'],confirmed:['confirmed','fulfilled','cancelled'],fulfilled:['fulfilled'],cancelled:['cancelled']};if(!allowed[o.status].includes(d.status)||!['paid','unpaid'].includes(d.payment_status)||o.payment_status==='paid'&&d.payment_status!=='paid'||d.status==='cancelled'&&(o.payment_status==='paid'||d.payment_status==='paid'))fail('Invalid order transition or payment reconciliation required.');db.exec('BEGIN IMMEDIATE');try{if(d.status==='cancelled'&&o.status!=='cancelled')for(const i of o.items){const p=one('products',i.product_id,req.siteId);if(p)update('products',p.id,req.siteId,{stock:p.stock+i.quantity,version:p.version+1})}update('orders',o.id,req.siteId,{status:d.status,payment_status:d.payment_status});log(req.siteId,'updated order',o.reference);db.exec('COMMIT');res.json({ok:true})}catch(e){db.exec('ROLLBACK');throw e}});
}
