import {validateBlocks} from './block-schema.mjs';
export function registerEditing(app, { all, one, insert, update, log, db }) {
  for(const p of all('pages'))if(!p.version)update('pages',p.id,p.website_id,{version:1});
  function requirePage(req,res) { const p=one('pages',req.params.page,req.siteId);if(!p){res.status(404).json({message:'Page not found.'});return null}return p }
  function sameVersion(req,res,p) { if(!Number.isInteger(req.body.version)){res.status(422).json({message:'The page version is required.'});return false}if(req.body.version!==p.version){res.status(409).json({message:'This page changed in another session. Reload the latest version before saving.'});return false}return true }
  const content=d=>({title:d.title,slug:d.slug,language:d.language,status:d.status,blocks:d.blocks,seo:d.seo||{},publish_at:d.publish_at||null});
  function valid(req,res) {const d=req.body;if(!d.title?.trim()||d.title.length>190||!d.slug?.match(/^[a-z0-9]+(?:-[a-z0-9]+)*$/)||!['en','fa','ps','ar'].includes(d.language)||!['draft','published','scheduled','archived'].includes(d.status)||!Array.isArray(d.blocks)||d.blocks.length>100){res.status(422).json({message:'A title, valid slug, language, status and at most 100 blocks are required.'});return false}validateBlocks(d.blocks);return true}
  app.get('/api/websites/:site/pages/:page/editor',(req,res)=>{const p=requirePage(req,res);if(!p)return;res.json({page:p,autosave:all('autosaves',req.siteId).find(a=>a.page_id===p.id&&a.user_id===1)||null})});
  app.put('/api/websites/:site/pages/:page/autosave',(req,res)=>{const p=requirePage(req,res);if(!p||!valid(req,res)||!sameVersion(req,res,p))return;const old=all('autosaves',req.siteId).find(a=>a.page_id===p.id&&a.user_id===1);if((old?.revision||0)!==(req.body.autosave_version||0))return res.status(409).json({message:'Your working copy changed in another tab. Reload before saving.'});const data={page_id:p.id,user_id:1,base_version:p.version,revision:(old?.revision||0)+1,snapshot:content(req.body)};const a=old?update('autosaves',old.id,req.siteId,data):insert('autosaves',req.siteId,data);res.json({autosave_version:a.revision,base_version:p.version,saved_at:a.updated_at})});
  app.delete('/api/websites/:site/pages/:page/autosave',(req,res)=>{const p=requirePage(req,res);if(!p)return;const a=all('autosaves',req.siteId).find(a=>a.page_id===p.id&&a.user_id===1);if(a&&a.revision!==req.body.autosave_version)return res.status(409).json({message:'Working copy changed in another tab.'});if(a)db.prepare('DELETE FROM records WHERE id=? AND kind=?').run(a.id,'autosaves');res.json({ok:true})});
  function save(req,res){if(!valid(req,res))return;const old=req.params.page?requirePage(req,res):null;if(req.params.page&&(!old||!sameVersion(req,res,old)))return;if(all('pages',req.siteId).some(p=>p.id!==old?.id&&p.slug===req.body.slug&&p.language===req.body.language))return res.status(422).json({message:'A page with this slug and language already exists.'});if(req.body.status==='scheduled'&&(!req.body.publish_at||!Number.isFinite(Date.parse(req.body.publish_at))||Date.parse(req.body.publish_at)<=Date.now()))return res.status(422).json({message:'Choose a valid future publication time.'});const d={...content(req.body),publish_at:req.body.status==='scheduled'?req.body.publish_at:null,version:(old?.version||0)+1};if(old)insert('revisions',req.siteId,{page_id:old.id,snapshot:old});const p=old?update('pages',old.id,req.siteId,d):insert('pages',req.siteId,{...d,website_id:req.siteId});const auto=all('autosaves',req.siteId).find(a=>a.page_id===p.id&&a.user_id===1&&a.revision===req.body.autosave_version);if(auto)db.prepare('DELETE FROM records WHERE id=? AND kind=?').run(auto.id,'autosaves');log(req.siteId,p.status==='published'?'published a page':'saved a page',p.title);res.json(p)}
  app.post('/api/websites/:site/pages',save);app.put('/api/websites/:site/pages/:page',save);
  app.post('/api/websites/:site/pages/:page/revisions/:revision/restore',(req,res)=>{const p=requirePage(req,res);if(!p||!sameVersion(req,res,p))return;const rev=one('revisions',req.params.revision,req.siteId);if(!rev||rev.page_id!==p.id)return res.status(404).json({message:'Revision not found.'});insert('revisions',req.siteId,{page_id:p.id,snapshot:p});const result=update('pages',p.id,req.siteId,{title:rev.snapshot.title,blocks:rev.snapshot.blocks,seo:rev.snapshot.seo,status:'draft',publish_at:null,version:p.version+1});log(req.siteId,'restored a revision as draft',result.title);res.json(result)});
}
