import sharp from 'sharp';import path from 'node:path';import{randomUUID}from'node:crypto';import{unlink}from'node:fs/promises';
export function registerMedia(app,{all,one,insert,update,remove,log,root}) {
 for(const m of all('media'))if(!m.folder_id){const f=all('folders',m.website_id).find(f=>f.name===m.folder);if(f)update('media',m.id,m.website_id,{folder_id:f.id})}
 app.get('/api/websites/:site/media-folders',(req,res)=>res.json(all('folders',req.siteId)));
 function folderSave(req,res){const d=req.body,id=+req.params.folder,old=id?one('folders',id,req.siteId):null;if(id&&!old)return res.status(404).json({message:'Folder not found.'});if(!d.name?.trim()||d.name.length>100||all('folders',req.siteId).some(f=>f.name===d.name&&f.id!==id))return res.status(422).json({message:'Choose a unique folder name (up to 100 characters).'});let parent=d.parent_id,seen=[];while(parent){const p=one('folders',parent,req.siteId);if(!p||parent===id||seen.includes(parent)||seen.length>10)return res.status(422).json({message:'Invalid parent or folder cycle.'});seen.push(parent);parent=p.parent_id}const data={name:d.name,parent_id:d.parent_id||null,website_id:req.siteId};const record=old?update('folders',id,req.siteId,data):insert('folders',req.siteId,data);for(const m of all('media',req.siteId))if(m.folder_id===id)update('media',m.id,req.siteId,{folder:d.name});log(req.siteId,'saved media folder',d.name);res.json(record)}
 app.post('/api/websites/:site/media-folders',folderSave);app.put('/api/websites/:site/media-folders/:folder',folderSave);
 app.delete('/api/websites/:site/media-folders/:folder',(req,res)=>{const id=+req.params.folder;if(!one('folders',id,req.siteId))return res.status(404).json({message:'Folder not found.'});if(all('folders',req.siteId).some(f=>f.parent_id===id)||all('media',req.siteId).some(m=>m.folder_id===id))return res.status(422).json({message:'Move all files and subfolders first.'});remove('folders',id,req.siteId);res.json({ok:true})});
 app.put('/api/websites/:site/media/:media',(req,res)=>{const d=req.body;if(!one('media',req.params.media,req.siteId))return res.status(404).json({message:'Media not found.'});if(!d.name?.trim()||d.name.length>190)return res.status(422).json({message:'A file name is required (up to 190 characters).'});const folder=d.folder_id?one('folders',d.folder_id,req.siteId):null;if(d.folder_id&&!folder)return res.status(422).json({message:'Folder does not belong to this website.'});res.json(update('media',req.params.media,req.siteId,{name:d.name,alt:d.alt||'',caption:d.caption||'',description:d.description||'',folder_id:folder?.id||null,folder:folder?.name||'All files'}))});
 app.post('/api/websites/:site/media/:media/transform',async(req,res)=>{const m=one('media',req.params.media,req.siteId),d=req.body;if(!m)return res.status(404).json({message:'Media not found.'});if(!['image/jpeg','image/png','image/webp'].includes(m.mime))return res.status(422).json({message:'Edit JPG, PNG or WEBP images only.'});if(!['jpeg','png','webp'].includes(d.format)||!d.name?.trim()||d.name.length>180||!Number.isInteger(d.width)||d.width<16||d.width>4096||!Number.isInteger(d.quality)||d.quality<20||d.quality>100||[d.x,d.y,d.crop_width,d.crop_height].some(v=>typeof v!=='number'||!Number.isFinite(v))||d.x<0||d.y<0||d.crop_width<1||d.crop_height<1||d.x+d.crop_width>100||d.y+d.crop_height>100)return res.status(422).json({message:'Invalid crop, output dimensions, quality or format.'});let source;if(m.url.startsWith('/storage/'))source=path.join(root,'uploads',path.basename(m.url));else if(m.url.startsWith('/images/'))source=path.resolve(import.meta.dirname,'../frontend/public/images',path.basename(m.url));else return res.status(422).json({message:'Remote images cannot be processed. Upload the image first.'});const image=sharp(source,{limitInputPixels:16000000}).autoOrient();const raw=await image.toBuffer();const meta=await sharp(raw).metadata();const crop={left:Math.floor(d.x/100*meta.width),top:Math.floor(d.y/100*meta.height),width:Math.max(1,Math.floor(d.crop_width/100*meta.width)),height:Math.max(1,Math.floor(d.crop_height/100*meta.height))};const height=Math.max(1,Math.round(d.width*crop.height/crop.width));if(height>4096||height*d.width>4000000)return res.status(422).json({message:'Output must be at most 4096 px per edge and 4 megapixels.'});const name=randomUUID()+'.'+d.format,destination=path.join(root,'uploads',name);let edited=sharp(raw).extract(crop).resize(d.width,height);if(d.format==='jpeg')edited=edited.flatten({background:'#ffffff'});const result=await edited.toFormat(d.format,{quality:d.quality}).toFile(destination);try{const record=insert('media',req.siteId,{website_id:req.siteId,name:d.name+'.'+d.format,url:'/storage/'+name,mime:'image/'+d.format,size:result.size,width:result.width,height:result.height,alt:m.alt||'',folder_id:m.folder_id||null,folder:m.folder||'All files',caption:m.caption||''});log(req.siteId,'created edited image',record.name);res.status(201).json(record)}catch(e){await unlink(destination).catch(()=>{});throw e}});
}
