// LOCAL PREVIEW ONLY. The deployable application uses backend/ (Laravel + MySQL).
import{registerBusinessPublic,registerBusinessAdmin}from'./business.mjs';
import express from 'express';
import {registerEditing} from './editing.mjs';
import {registerAccess} from './access.mjs';
import {registerPublic} from './public.mjs';
import {registerMenus} from './menus.mjs';
import {registerMedia} from './media.mjs';
import {registerPresets} from './presets.mjs';
import {validateBlocks} from './block-schema.mjs';
import multer from 'multer';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import path from 'node:path';
const root=process.env.CMS_PREVIEW_DATA||path.resolve(import.meta.dirname,'../.runtime');mkdirSync(root+'/uploads',{recursive:true});
const db=new DatabaseSync(root+'/preview.sqlite');db.exec('PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS records (id INTEGER PRIMARY KEY AUTOINCREMENT, kind TEXT NOT NULL, site INTEGER, data TEXT NOT NULL); CREATE INDEX IF NOT EXISTS scope ON records(kind,site); CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, created INTEGER);');
const all=(kind,site)=>db.prepare('SELECT * FROM records WHERE kind=?'+(site!==undefined?' AND site=?':'')+' ORDER BY id DESC').all(...(site!==undefined?[kind,site]:[kind])).map(r=>({...JSON.parse(r.data),id:r.id}));
const one=(kind,id,site)=>all(kind,site).find(r=>r.id===+id);
const insert=(kind,site,data)=>{const info=db.prepare('INSERT INTO records(kind,site,data) VALUES(?,?,?)').run(kind,site,JSON.stringify({...data,created_at:new Date().toISOString(),updated_at:new Date().toISOString()}));return one(kind,Number(info.lastInsertRowid),site??undefined)};
const update=(kind,id,site,data)=>{const old=one(kind,id,site);if(!old)throw Object.assign(new Error('Record not found'),{status:404});db.prepare('UPDATE records SET data=? WHERE id=? AND kind=?').run(JSON.stringify({...old,...data,updated_at:new Date().toISOString()}),+id,kind);return one(kind,id,site)};
const remove=(kind,id,site)=>{if(!one(kind,id,site))throw Object.assign(new Error('Record not found'),{status:404});db.prepare('DELETE FROM records WHERE kind=? AND id=? AND site=?').run(kind,+id,site)};
const log=(site,action,subject)=>insert('activity',site,{website_id:site,user:'Alex Morgan',action,subject});
const themes={Evergreen:'#286b54',Editorial:'#855039',Studio:'#62588b',Scholar:'#274e75'};
const appearance=theme=>({primary:themes[theme]||themes.Evergreen,background:'#faf9f6',surface:'#ffffff',text:'#263d35',heading:'#193c30',font:'Inter',radius:12,container:1200,mode:'light',header:'centered',footer:'simple'});
const photos={studio:'/images/studio.jpg',university:'/images/university.jpg',shop:'/images/shop.jpg',journal:'/images/studio.jpg'};
function provision(data){db.exec('BEGIN');try{const site=insert('websites',null,{name:data.name,domain:data.domain,type:data.type||'Business',description:data.description||'',theme:data.theme||'Evergreen',image:data.image||photos.studio,color:themes[data.theme]||themes.Evergreen,status:data.status||'draft',default_language:data.default_language||'en',default_currency:data.default_currency||'USD',languages:[...new Set(['en','fa','ps','ar',...(data.languages||[])])],currencies:[...new Set(['USD','AFN','EUR','GBP','AED','SAR','PKR',...(data.currencies||[])])],appearance:appearance(data.theme),settings:{tagline:data.description||'',contact_email:'',seo:{index:true}}});const blocks=[{id:randomBytes(6).toString('hex'),type:'Hero',title:data.hero||'Thoughtfully made.\nBeautifully different.',text:data.description||'A new perspective. A space for your ideas. Welcome to what comes next.',image:site.image,button:'Explore our work'},{id:randomBytes(6).toString('hex'),type:'Text',title:'Good things begin with a little inspiration.',text:'We believe in the power of thoughtful design, meaningful connections, and creating something that lasts.'}];insert('pages',site.id,{website_id:site.id,title:'Home',slug:'home',version:1,language:site.default_language,status:data.status==='published'?'published':'draft',blocks,seo:{title:site.name,description:site.description}});insert('templates',site.id,{website_id:site.id,name:'Getting started',type:'Page',blocks});insert('menus',site.id,{website_id:site.id,name:'Main navigation',location:'header',language:'en',version:1,items:[{key:randomBytes(8).toString('hex'),label:'Home',url:'home',children:[],new_tab:false},{key:randomBytes(8).toString('hex'),label:'Our story',url:'#about',children:[],new_tab:false},{key:randomBytes(8).toString('hex'),label:'Get in touch',url:'mailto:hello@example.com',children:[],new_tab:false}]});for(const [name,content]of Object.entries({'Announcement Bar':{enabled:false,text:'Something new is on its way.'},'Global CTA':{enabled:false,title:'Let’s create something meaningful.',text:'We would love to hear from you.',button:'Get in touch',link:'mailto:hello@example.com'},Header:{title:site.name},Footer:{text:`© ${new Date().getFullYear()} ${site.name}. All rights reserved.`},Navigation:{items:[{label:'Home',url:'home'}]}}))insert('components',site.id,{name,content});for(const currency of site.currencies)insert('currencies',site.id,{currency_code:currency,exchange_rate:currency==='USD'?1:currency==='AFN'?70:currency==='EUR'?0.92:1,position:'before',rate_source:'manual'});insert('folders',site.id,{name:'Brand assets'});log(site.id,'created a website',site.name);db.exec('COMMIT');return site}catch(e){db.exec('ROLLBACK');throw e}}
if(!all('websites').length){
const a=provision({name:'Evergreen Studio',domain:'evergreen.studio',type:'Agency',description:'Thoughtful spaces. Lasting impressions.',theme:'Evergreen',status:'published',image:photos.studio});
const b=provision({name:'Westbridge University',domain:'westbridge.edu',type:'University',description:'A world of possibility starts here.',theme:'Scholar',status:'published',image:photos.university,hero:'Your future.\nWithout limits.'});
const c=provision({name:'Forma & Field',domain:'formaandfield.com',type:'E-commerce',description:'Everyday objects. Exceptionally considered.',theme:'Editorial',status:'draft',image:photos.shop,hero:'Less, but better.'});
const d=provision({name:'The Quiet Journal',domain:'thequietjournal.com',type:'Blog',description:'Stories for a slower, more intentional life.',theme:'Evergreen',status:'published',image:photos.journal,hero:'Make room for\nthe everyday.'});
for(const s of [a,b,c,d]){for(const title of ['About us','Contact','Our work'])insert('pages',s.id,{website_id:s.id,title,version:1,slug:title.toLowerCase().replaceAll(' ','-'),language:'en',status:title==='Our work'?'draft':'published',blocks:[{id:randomBytes(4).toString('hex'),type:'Text',title,text:`Welcome to ${s.name}. We'd love to share our story with you.`}],seo:{}});for(const [name,url]of Object.entries(photos))insert('media',s.id,{website_id:s.id,name:name+'-editorial.jpg',url,mime:'image/jpeg',size:248000,alt:name+' editorial photography',folder:'Brand assets'});}
log(a.id,'published a page','Home');log(b.id,'updated website settings','Westbridge University');log(c.id,'uploaded media','Brand photography');log(d.id,'saved a page','Our work');
}
const app=express();app.use(express.json({limit:'3mb'}));app.use('/storage',express.static(root+'/uploads',{setHeaders(res){res.setHeader('X-Content-Type-Options','nosniff')}}));
app.get('/api/csrf',(req,res)=>res.json({token:'local-preview'}));const user={id:1,name:'Alex Morgan',email:'alex@atelier.local',role:'Super Admin'};
function session(res){const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?)').run(token,Date.now());res.cookie('atelier_preview',token,{httpOnly:true,sameSite:'lax',maxAge:86400000});}
app.get('/api/auth/me',(req,res)=>{session(res);res.json(user)}); // Deliberate anonymous demo access; NEVER deploy this adapter.
app.post('/api/auth/login',(req,res)=>{session(res);res.json(user)});
app.post('/api/auth/logout',(req,res)=>{const token=req.headers.cookie?.match(/atelier_preview=([^;]+)/)?.[1];if(token)db.prepare('DELETE FROM sessions WHERE token=?').run(token);res.clearCookie('atelier_preview');res.json({ok:true})});
const enriched=s=>({...s,pages_count:all('pages',s.id).length});
registerBusinessPublic(app,{all,one,insert,update,db});
registerPublic(app,{all,one});
app.use('/api',(req,res,next)=>{const token=req.headers.cookie?.match(/atelier_preview=([^;]+)/)?.[1];if(!token||!db.prepare('SELECT * FROM sessions WHERE token=? AND created>?').get(token,Date.now()-86400000))return res.status(401).json({message:'Please sign in to continue.'});next()});
app.get('/api/dashboard',(req,res)=>{const sites=all('websites').reverse();res.json({mode:'Local preview · SQLite',websites:sites.map(enriched),counts:{websites:sites.length,pages:all('pages').length,published:all('pages').filter(p=>p.status==='published').length,drafts:all('pages').filter(p=>p.status==='draft').length,media:all('media').length,users:1},activity:all('activity').slice(0,20)})});
app.post('/api/websites',(req,res)=>{const d=req.body;if(!d.name?.trim()||!d.domain?.match(/^[a-z0-9.-]+$/i))return res.status(422).json({message:'Enter a website name and valid domain (without https://).'});if(all('websites').some(s=>s.domain===d.domain))return res.status(422).json({message:'That domain is already connected to a website.'});res.status(201).json(enriched(provision(d)))});
app.param('site',(req,res,next,id)=>{if(!one('websites',id))return res.status(404).json({message:'Website not found.'});req.siteId=+id;next()});
app.put('/api/websites/:site',(req,res)=>{const d=req.body;const fields={};for(const key of ['name','domain','description','status','default_language','default_currency'])if(d[key]!==undefined)fields[key]=d[key];if(d.domain&&all('websites').some(s=>s.id!==req.siteId&&s.domain===d.domain))return res.status(422).json({message:'This domain is already in use.'});res.json(enriched(update('websites',req.siteId,undefined,fields)));log(req.siteId,'updated website settings',d.name||'Website')});
app.get('/api/websites/:site/pages',(req,res)=>res.json(all('pages',req.siteId)));
registerEditing(app,{all,one,insert,update,log,db});
registerAccess(app,{all,one,insert,update,remove,log,user,db});
registerMenus(app,{all,one,insert,update,log});
registerMedia(app,{all,one,insert,update,remove,log,root});
registerPresets(app,{all,one,insert,update,remove,log});
registerBusinessAdmin(app,{all,one,insert,update,remove,log,db});
app.delete('/api/websites/:site/pages/:page',(req,res)=>{remove('pages',req.params.page,req.siteId);for(const kind of ['autosaves','revisions'])for(const r of all(kind,req.siteId))if(r.page_id===+req.params.page)remove(kind,r.id,req.siteId);log(req.siteId,'deleted a page','Page');res.json({ok:true})});
app.get('/api/websites/:site/pages/:page/revisions',(req,res)=>res.json(all('revisions',req.siteId).filter(r=>r.page_id===+req.params.page)));
app.put('/api/websites/:site/appearance',(req,res)=>{if(!themes[req.body.theme]||!/^#[a-f\d]{6}$/i.test(req.body.appearance?.primary))return res.status(422).json({message:'Choose a valid theme and color.'});res.json(enriched(update('websites',req.siteId,undefined,{theme:req.body.theme,appearance:req.body.appearance,color:req.body.appearance.primary})));log(req.siteId,'customized the appearance','Theme & Appearance')});
const upload=multer({storage:multer.diskStorage({destination:root+'/uploads',filename:(req,file,cb)=>cb(null,randomBytes(16).toString('hex')+path.extname(file.originalname).toLowerCase())}),limits:{fileSize:20*1024*1024,files:20},fileFilter:(req,file,cb)=>cb(null,/\.(jpe?g|png|webp|gif|mp4|pdf|docx?|xlsx?)$/i.test(file.originalname))});
app.get('/api/websites/:site/media',(req,res)=>res.json(all('media',req.siteId)));
app.post('/api/websites/:site/media',upload.array('files[]',20),(req,res)=>{if(!req.files?.length)return res.status(422).json({message:'Unsupported file. Use JPG, PNG, WEBP, GIF, MP4, PDF or Office documents. SVG requires sanitization and is not accepted yet.'});res.status(201).json(req.files.map(f=>{log(req.siteId,'uploaded media',f.originalname);return insert('media',req.siteId,{website_id:req.siteId,name:f.originalname,url:'/storage/'+f.filename,mime:f.mimetype,size:f.size,alt:'',folder:'Uploads'})}))});
app.put('/api/websites/:site/media/:media',(req,res)=>res.json(update('media',req.params.media,req.siteId,{name:req.body.name,alt:req.body.alt||'',caption:req.body.caption||'',folder:req.body.folder||'Uploads'})));
app.delete('/api/websites/:site/media/:media',(req,res)=>{remove('media',req.params.media,req.siteId);res.json({ok:true})});
for(const kind of ['templates','translations','currencies','components']){
app.get('/api/websites/:site/'+kind,(req,res)=>res.json(all(kind,req.siteId)));
app.post('/api/websites/:site/'+kind,(req,res)=>{const d=req.body;if(kind==='templates')validateBlocks(d.blocks);if(kind==='components'){if(!['Header','Footer','Announcement Bar','Global CTA'].includes(d.name)||!d.content||typeof d.content!=='object'||Object.keys(d.content).some(k=>!['enabled','title','text','logo','link','button'].includes(k)))return res.status(422).json({message:'Choose a supported component and content fields.'});if(d.content.link&&!/^(https?:\/\/[^\s]+|mailto:[^\s]+|#[a-zA-Z0-9_-]+|\/?[a-zA-Z0-9_/-]+)$/.test(d.content.link))return res.status(422).json({message:'Enter a safe page slug, anchor, https:// or mailto: link.'})}let old;if(kind==='currencies')old=all(kind,req.siteId).find(x=>x.currency_code===d.currency_code);if(kind==='translations')old=all(kind,req.siteId).find(x=>x.key===d.key&&x.language===d.language);if(kind==='menus')old=all(kind,req.siteId).find(x=>x.location===d.location);if(kind==='components')old=all(kind,req.siteId).find(x=>x.name===d.name);res.json(old?update(kind,old.id,req.siteId,d):insert(kind,req.siteId,d));log(req.siteId,'updated '+kind,d.name||d.key||d.currency_code)});
}
app.use((err,req,res,next)=>{console.error(err.message);res.status(err.status||422).json({message:err.message||'Unable to complete the request.'})});
setInterval(()=>{for(const p of all('pages'))if(p.status==='scheduled'&&p.publish_at&&Date.parse(p.publish_at)<=Date.now()){update('pages',p.id,p.website_id,{status:'published',publish_at:null,version:p.version+1});log(p.website_id,'published scheduled page',p.title)}},60000).unref();
const port=Number(process.env.CMS_PREVIEW_PORT||8000);app.listen(port,'0.0.0.0',()=>console.log('Atelier LOCAL DEVELOPMENT API listening on '+port+'. Anonymous preview access enabled. Do not deploy.'));
