import fs from'node:fs';import path from'node:path';import ts from'typescript';import{parse}from'@vue/compiler-sfc';import{parse as parseTemplate}from'@vue/compiler-dom';
const root=path.resolve(import.meta.dirname,'..'),dir=root+'/src/locales',keys=new Set();
const collect=code=>{const file=ts.createSourceFile('fragment.ts',code,ts.ScriptTarget.Latest,true);const walk=n=>{if(ts.isCallExpression(n)&&['t','$t'].includes(n.expression.getText(file))){const arg=n.arguments[0];if(arg){const read=x=>{if(ts.isStringLiteral(x)&&x.text)keys.add(x.text);else if(ts.isConditionalExpression(x)){read(x.whenTrue);read(x.whenFalse)}};read(arg)}}if(ts.isPropertyAssignment(n)&&['label','note','tag'].includes(n.name.getText(file).replaceAll("'",''))&&ts.isStringLiteral(n.initializer))keys.add(n.initializer.text);ts.forEachChild(n,walk)};walk(file)};
for(const file of [root+'/src/App.vue',...fs.readdirSync(root+'/src/components').filter(f=>f.endsWith('.vue')).map(f=>root+'/src/components/'+f)]){const{descriptor:d}=parse(fs.readFileSync(file,'utf8'));collect(d.scriptSetup?.content||'');if(d.template){const walk=n=>{if(n.type===5)collect(n.content.content);if(n.type===1){for(const p of n.props)if(p.type===7&&p.exp)collect(p.exp.content)}for(const c of n.children||[])walk(c)};walk(parseTemplate(d.template.content))}}
const catalogs={fa:{},ps:{},ar:{}},aliases=JSON.parse(fs.readFileSync(dir+'/aliases.json','utf8'));
for(const row of fs.readFileSync(dir+'/catalog.tsv','utf8').trim().split('\n')){const [key,...values]=row.split('\t');if(values.length!==3)throw Error('Malformed translation: '+key);['fa','ps','ar'].forEach((l,i)=>catalogs[l][key]=values[i]);keys.add(key)}
const exact=Object.keys(catalogs.fa),lookup=s=>exact.find(k=>k.toLowerCase()===s.toLowerCase());
for(let iteration=0;iteration<5;iteration++)for(const [key,value]of Object.entries(aliases)){keys.add(key);const target=catalogs.fa[value]?value:lookup(value);if(target)for(const l of['fa','ps','ar'])catalogs[l][key]=catalogs[l][target]}
for(const key of keys){if(catalogs.fa[key])continue;const same=lookup(key);if(same){for(const l of['fa','ps','ar'])catalogs[l][key]=catalogs[l][same];continue}const op=/^(Save|Delete|Remove|Add|Search) (.+)$/i.exec(key);if(op){const noun=lookup(op[2]);if(noun)for(const l of['fa','ps','ar'])catalogs[l][key]=l==='ps'?catalogs[l][noun]+' '+catalogs[l][op[1]]:catalogs[l][op[1]]+' '+catalogs[l][noun]}}
const technical=['components.Footer.text','components.Global CTA.button','components.Header.title','navigation.home','e.g. Evergreen Studio','e.g. evergreen.studio'];for(const k of technical)for(const l of['fa','ps','ar'])catalogs[l][k]=k;
for(const l of['fa','ps','ar'])fs.writeFileSync(dir+'/'+l+'.json',JSON.stringify(catalogs[l],null,2)+'\n');
const missing=[...keys].filter(k=>!catalogs.fa[k]).sort();fs.writeFileSync(dir+'/en.json',JSON.stringify(Object.fromEntries([...keys].sort().map(k=>[k,k])),null,2)+'\n');fs.writeFileSync('/tmp/locale-missing.json',JSON.stringify(missing,null,2));console.log(`${keys.size} messages; ${missing.length} missing`);if(process.argv.includes('--check')&&missing.length)process.exit(1);
