<?php
namespace Tests\Feature;
use App\Domains\Websites\ProvisionWebsite;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{DB,Mail};
use Illuminate\Support\Str;
use Tests\TestCase;
class BusinessModulesTest extends TestCase {
 use RefreshDatabase;
 private $site;private $other;private $admin;
 protected function setUp():void{parent::setUp();$this->seed();$this->admin=User::factory()->create();$this->admin->forceFill(['role_id'=>DB::table('roles')->where('name','Super Admin')->value('id')])->save();$this->actingAs($this->admin);$this->site=app(ProvisionWebsite::class)->create(['name'=>'Store','domain'=>'store.example.com'],$this->admin->id);$this->site->update(['status'=>'published']);$this->other=app(ProvisionWebsite::class)->create(['name'=>'Other','domain'=>'otherstore.example.com'],$this->admin->id);}
 private function product(int $stock=4):array{return $this->postJson("/api/websites/{$this->site->id}/products",['name'=>'Kit','sku'=>'KIT','description'=>'Care kit','image'=>'','currency'=>$this->site->default_currency,'price_minor'=>1250,'stock'=>$stock,'active'=>true])->assertOk()->json();}
 private function checkout(array $product):array{return ['idempotency_key'=>(string)Str::uuid(),'name'=>'Buyer','email'=>'buyer@example.com','phone'=>'0700000000','address'=>'A delivery address in Kabul','consent'=>true,'items'=>[['product_id'=>$product['id'],'quantity'=>2,'price_minor'=>1]]];}
 public function test_contact_requires_consent_and_messages_are_tenant_scoped():void{$path="/api/public/websites/{$this->site->id}/contact";$data=['name'=>'Visitor','email'=>'visitor@example.com','message'=>'Please send more information.','language'=>'fa','consent'=>true,'company'=>''];$this->postJson($path,[...$data,'consent'=>false])->assertUnprocessable();$this->postJson($path,$data)->assertCreated();$id=DB::table('submissions')->value('id');$this->putJson("/api/websites/{$this->other->id}/submissions/$id",['status'=>'read'])->assertNotFound();$this->getJson("/api/websites/{$this->site->id}/inbox")->assertOk()->assertJsonPath('messages.total',1);}
 public function test_newsletter_token_is_private_expiring_and_single_use():void{$body='';Mail::shouldReceive('raw')->once()->andReturnUsing(function($text,$callback)use(&$body){$body=$text;});$path="/api/public/websites/{$this->site->id}";$this->postJson($path.'/newsletter',['email'=>'reader@example.com','language'=>'en','consent'=>true])->assertStatus(202)->assertJsonMissingPath('token');$row=DB::table('subscribers')->first();$this->assertSame('pending',$row->status);preg_match('/newsletter=([^&\s]+)/',$body,$m);$token=urldecode($m[1]);$this->assertNotSame($token,$row->token_hash);$d=['email'=>$row->email,'token'=>$token,'action'=>'confirm'];$this->postJson($path.'/subscription',$d)->assertOk();$this->postJson($path.'/subscription',$d)->assertUnprocessable();$this->assertDatabaseHas('subscribers',['id'=>$row->id,'status'=>'subscribed','token_hash'=>null]);}
 public function test_checkout_ignores_client_prices_and_is_idempotent():void{$p=$this->product();$data=$this->checkout($p);$path="/api/public/websites/{$this->site->id}/store/checkout";$r=$this->postJson($path,$data)->assertCreated()->assertJsonPath('total_minor',2500);$this->postJson($path,$data)->assertOk()->assertJsonPath('reference',$r->json('reference'));$this->assertDatabaseCount('orders',1);$this->assertDatabaseHas('products',['id'=>$p['id'],'stock'=>2]);$this->postJson($path,[...$data,'name'=>'Changed'])->assertConflict();}
 public function test_failed_checkout_rolls_back_stock_and_stale_product_edits_fail():void{$p=$this->product();$d=$this->checkout($p);$d['items'][]=['product_id'=>999999,'quantity'=>1];$this->postJson("/api/public/websites/{$this->site->id}/store/checkout",$d)->assertUnprocessable();$this->assertDatabaseHas('products',['id'=>$p['id'],'stock'=>4]);$this->postJson("/api/public/websites/{$this->site->id}/store/checkout",$this->checkout($p))->assertCreated();$this->putJson("/api/websites/{$this->site->id}/products/{$p['id']}",$p)->assertConflict();}
 public function test_cancel_restores_stock_once_and_forbids_cross_site_orders():void{$p=$this->product();$this->postJson("/api/public/websites/{$this->site->id}/store/checkout",$this->checkout($p))->assertCreated();$id=DB::table('orders')->value('id');$d=['status'=>'cancelled','payment_status'=>'unpaid','expected_status'=>'pending','expected_payment_status'=>'unpaid'];$this->putJson("/api/websites/{$this->other->id}/orders/$id",$d)->assertNotFound();$this->putJson("/api/websites/{$this->site->id}/orders/$id",$d)->assertOk();$this->putJson("/api/websites/{$this->site->id}/orders/$id",$d)->assertConflict();$this->assertDatabaseHas('products',['id'=>$p['id'],'stock'=>4]);}
 public function test_reader_cannot_access_customer_data_or_commerce():void{$u=User::factory()->create();$role=DB::table('roles')->where('name','Editor')->value('id');$u->forceFill(['role_id'=>$role])->save();DB::table('website_user')->insert(['website_id'=>$this->site->id,'user_id'=>$u->id,'role_id'=>$role]);$this->actingAs($u)->getJson("/api/websites/{$this->site->id}/inbox")->assertForbidden();$this->getJson("/api/websites/{$this->site->id}/orders")->assertForbidden();$this->getJson("/api/websites/{$this->site->id}/products")->assertForbidden();}
}
