<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('roles', function(Blueprint $t){$t->id();$t->string('name')->unique();$t->json('permissions');$t->timestamps();});
  Schema::table('users', function(Blueprint $t){$t->foreignId('role_id')->nullable()->constrained();});
  Schema::create('languages', function(Blueprint $t){$t->string('code',10)->primary();$t->string('name');$t->string('native_name');$t->string('direction',3)->default('ltr');});
  Schema::create('currencies', function(Blueprint $t){$t->string('code',3)->primary();$t->string('name');$t->string('symbol');$t->unsignedTinyInteger('decimals')->default(2);});
  Schema::create('themes', function(Blueprint $t){$t->id();$t->string('name');$t->string('category');$t->json('tokens');$t->timestamps();});
  Schema::create('websites', function(Blueprint $t){$t->id();$t->string('name');$t->string('domain')->unique();$t->text('description')->nullable();$t->string('type')->default('Business');$t->string('status')->default('draft')->index();$t->foreignId('theme_id')->constrained();$t->string('theme')->default('Evergreen');$t->string('color')->default('#286b54');$t->string('image')->nullable();$t->string('default_language',10)->default('en');$t->string('default_currency',3)->default('USD');$t->foreign('default_language')->references('code')->on('languages');$t->foreign('default_currency')->references('code')->on('currencies');$t->foreignId('created_by')->constrained('users');$t->timestamps();});
  Schema::create('website_user', function(Blueprint $t){$t->foreignId('website_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('role_id')->constrained();$t->primary(['website_id','user_id']);});
  Schema::create('website_languages', function(Blueprint $t){$t->foreignId('website_id')->constrained()->cascadeOnDelete();$t->string('language_code',10);$t->foreign('language_code')->references('code')->on('languages');$t->primary(['website_id','language_code']);});
  Schema::create('website_currencies', function(Blueprint $t){$t->id();$t->foreignId('website_id')->constrained()->cascadeOnDelete();$t->string('currency_code',3);$t->foreign('currency_code')->references('code')->on('currencies');$t->decimal('exchange_rate',20,8)->default(1);$t->string('position')->default('before');$t->string('rate_source')->default('manual');$t->timestamps();$t->unique(['website_id','currency_code']);});
  foreach(['website_settings','theme_settings'] as $table) Schema::create($table,function(Blueprint $t){$t->id();$t->foreignId('website_id')->unique()->constrained()->cascadeOnDelete();$t->json('values');$t->timestamps();});
  Schema::create('pages',function(Blueprint $t){$t->id();$t->foreignId('website_id')->constrained()->cascadeOnDelete();$t->string('title');$t->string('slug');$t->string('language',10)->default('en');$t->string('status')->default('draft')->index();$t->json('blocks');$t->json('seo')->nullable();$t->foreignId('author_id')->constrained('users');$t->timestamp('publish_at')->nullable()->index();$t->timestamps();$t->unique(['website_id','slug','language']);});
  Schema::create('page_revisions',function(Blueprint $t){$t->id();$t->foreignId('page_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained();$t->json('snapshot');$t->timestamps();});
  Schema::create('media_folders',function(Blueprint $t){$t->id();$t->foreignId('website_id')->constrained()->cascadeOnDelete();$t->string('name');$t->unique(['website_id','name']);});
  Schema::create('media',function(Blueprint $t){$t->id();$t->foreignId('website_id')->constrained()->cascadeOnDelete();$t->foreignId('folder_id')->nullable()->constrained('media_folders')->nullOnDelete();$t->string('name');$t->string('path')->nullable();$t->text('url');$t->string('mime');$t->unsignedBigInteger('size');$t->string('alt')->default('');$t->text('caption')->nullable();$t->text('description')->nullable();$t->string('folder')->default('All files');$t->timestamps();});
  Schema::create('templates',function(Blueprint $t){$t->id();$t->foreignId('website_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('type');$t->json('blocks');$t->timestamps();});
  Schema::create('global_components',function(Blueprint $t){$t->id();$t->foreignId('website_id')->constrained()->cascadeOnDelete();$t->string('name');$t->json('content');$t->timestamps();$t->unique(['website_id','name']);});
  Schema::create('menus',function(Blueprint $t){$t->id();$t->foreignId('website_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('location');$t->string('language',10)->default('en');$t->timestamps();});
  Schema::create('menu_items',function(Blueprint $t){$t->id();$t->foreignId('menu_id')->constrained()->cascadeOnDelete();$t->foreignId('parent_id')->nullable()->constrained('menu_items')->cascadeOnDelete();$t->string('label');$t->string('url');$t->integer('position')->default(0);$t->timestamps();});
  Schema::create('translations',function(Blueprint $t){$t->id();$t->foreignId('website_id')->constrained()->cascadeOnDelete();$t->string('language',10);$t->string('key');$t->text('value');$t->timestamps();$t->unique(['website_id','language','key']);});
  Schema::create('activity_logs',function(Blueprint $t){$t->id();$t->foreignId('website_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action');$t->string('subject');$t->timestamps();$t->index(['website_id','created_at']);});
 }
 public function down(): void {foreach(['activity_logs','translations','menu_items','menus','global_components','templates','media','media_folders','page_revisions','pages','theme_settings','website_settings','website_currencies','website_languages','website_user','websites','themes','currencies','languages'] as $table)Schema::dropIfExists($table);Schema::table('users',fn(Blueprint $t)=>$t->dropConstrainedForeignId('role_id'));Schema::dropIfExists('roles');}
};
