<script setup lang="ts">
import {t} from "./i18n"
import { ref, computed, onMounted, watch, defineAsyncComponent } from 'vue'
import { useQuasar } from 'quasar'
import { useCms } from './store'
import { api, send } from './api'
import Icon from './components/Icon.vue'
import Dashboard from './components/Dashboard.vue'
import WebsiteWizard from './components/WebsiteWizard.vue'
const AccessManagement = defineAsyncComponent(() => import('./components/AccessManagement.vue'))
const Workspace = defineAsyncComponent(() => import('./components/Workspace.vue'))
const PublicSite = defineAsyncComponent(() => import('./components/PublicSite.vue'))
const cms = useCms(), q = useQuasar()
const view = ref('Overview'), wizard = ref(false), search = ref(''), mobileNav = ref(false), showSearch = ref(false), help = ref(false), notifications = ref(false), accountDialog = ref(false), passwordForm = ref({ current_password: '', password: '', password_confirmation: '' }), accountSaving = ref(false)
const email = ref(''), password = ref(''), signing = ref(false)
const publicMode = location.pathname.startsWith('/site/')
const nav = [{ label: 'Overview', icon: 'LayoutDashboard' }, { label: 'Websites', icon: 'PanelsTopLeft' }, { label: 'Media library', icon: 'Images' }, { label: 'Templates', icon: 'PanelTop' }]
const siteNav = [{label:'Pages',icon:'FileText'},{label:'Theme & Appearance',icon:'Palette'},{label:'Menus',icon:'Menu'},{label:'Global components',icon:'Layers'},{label:'Team',icon:'Users'},{label:'Inbox',icon:'Inbox'},{label:'Products',icon:'Package'},{label:'Orders',icon:'ShoppingBag'}]
const management = [{ label: 'Languages', icon: 'Languages' }, { label: 'Currencies', icon: 'CircleDollarSign' }, { label: 'Users & roles', icon: 'Users' }, { label: 'Activity log', icon: 'History' }, { label: 'Settings', icon: 'Settings2' }]
const label = t
const results = computed(() => cms.websites.filter(w => (w.name+' '+w.domain).toLowerCase().includes(search.value.toLowerCase())))
async function logout() { try { await api('/auth/logout', send('POST', {})); cms.user = null; cms.websites = []; cms.selectedId = null; view.value = 'Overview' } catch (e:any) { q.notify({type:'negative',message:t(e.message)}) } }
async function changePassword() { accountSaving.value = true; try { await api('/auth/password', send('PUT',passwordForm.value)); accountDialog.value=false; passwordForm.value={current_password:'',password:'',password_confirmation:''}; q.notify({type:'positive',message:t('Password changed. Other Laravel sessions have been revoked.')}) } catch(e:any) { q.notify({type:'negative',message:t(e.message)}) } finally { accountSaving.value=false } }
function navigate(name: string) { view.value = name; mobileNav.value = false; if (name === 'Overview' || name === 'Websites') cms.selectedId = null; else if (!cms.selectedId && cms.websites.length) cms.selectedId = cms.websites[0].id }
function manage(id: number, tab = 'Pages') { cms.selectedId = id; view.value = tab; showSearch.value = false; mobileNav.value = false }
async function login() { signing.value = true; try { cms.user = await api('/auth/login', send('POST', { email: email.value, password: password.value })); await cms.load() } catch (e: any) { if (e?.unreachable) cms.notice = t(e.message); q.notify({ type: 'negative', message: t(e.message) }) } finally { signing.value = false } }
onMounted(async () => { if (!publicMode) { const query=new URLSearchParams(location.search); await cms.init(); const id=Number(query.get('site')); if(cms.websites.some(w=>w.id===id)) cms.selectedId=id; const requested=query.get('view'); if(requested && [...nav,...siteNav,...management].some(x=>x.label===requested)) navigate(requested); } document.addEventListener('keydown', e => { if ((e.metaKey || e.ctrlKey) && e.key === 'k') { e.preventDefault(); showSearch.value = true } }) })
watch([view,()=>cms.selectedId],()=>{ if(!publicMode && cms.ready){ const params=new URLSearchParams(); params.set('view',view.value); if(cms.selectedId)params.set('site',String(cms.selectedId)); history.replaceState(null,'','/?'+params.toString()) } })
watch(() => cms.locale, locale => {document.documentElement.dir = locale==='en'?'ltr':'rtl';document.documentElement.lang=locale;localStorage.setItem('cms.locale',locale)}, {immediate:true})
</script>
<template>
<PublicSite v-if="publicMode" />
<div v-else-if="!cms.ready" class="loading-screen"><div class="brand-mark"><Icon name="Layers" :size="28" /></div><q-spinner color="primary" size="30px"/><p>{{ $t("Getting your workspace ready…") }}</p></div>
<div v-else-if="!cms.user" class="login-page"><form class="login-card" @submit.prevent="login"><div class="brand"><span class="brand-mark"><Icon name="Layers" :size="26"/></span>atelier<span class="brand-dot">.</span></div><h1>{{ $t("Welcome to your workspace.") }}</h1><p>{{ $t("A home for all the things you create.") }}</p><p v-if="cms.mode.includes('preview')" class="info-note">{{ $t("Local demo only. Do not enter real credentials. Reopen the demo workspace below.") }}</p><div v-if="cms.notice" class="info-note error-note" role="alert"><Icon name="Info" :size="16"/><span>{{ cms.notice }}</span></div><q-input v-if="!cms.mode.includes('preview')" outlined v-model="email" :label="$t('Email address')" type="email" required/><q-input v-if="!cms.mode.includes('preview')" outlined v-model="password" :label="$t('Password')" type="password" required/><q-btn unelevated color="primary" :label="$t(cms.mode.includes('preview')?'Open demo workspace':'Sign in')" type="submit" :loading="signing"/><small>{{ $t("Secure administration · Atelier CMS") }}</small></form></div>
<div v-else class="app-shell" :class="{ 'nav-open': mobileNav }">
<div v-if="mobileNav" class="nav-backdrop" @click="mobileNav = false"></div>
<aside class="sidebar">
<a class="brand" href="/" @click.prevent="navigate('Overview')"><span class="brand-mark"><Icon name="Layers" :size="25" /></span>atelier<span class="brand-dot">.</span></a>
<button class="workspace-select" @click="showSearch = true"><span class="workspace-avatar">A</span><span><strong>{{ $t("Acme workspace") }}</strong><small>{{ $t("Your creative headquarters") }}</small></span><Icon name="ChevronsUpDown" :size="15"/></button>
<div class="nav-caption">{{ $t("WORKSPACE") }}</div>
<nav><button v-for="item in nav" :key="item.label" :class="['nav-item', { active: view === item.label }]" @click="navigate(item.label)"><Icon :name="item.icon"/><span>{{ label(item.label) }}</span><span v-if="item.label === 'Websites'" class="nav-count">{{ cms.websites.length }}</span></button></nav>
<div class="nav-caption manage-caption">{{ $t(cms.selected?.name || 'WEBSITE TOOLS') }}</div><nav :aria-label="$t('Website tools')"><button v-for="item in siteNav" :key="item.label" :class="['nav-item',{active:view===item.label}]" @click="navigate(item.label)"><Icon :name="item.icon"/><span>{{ label(item.label) }}</span></button></nav><div class="nav-caption manage-caption">{{ $t("MANAGE") }}</div>
<nav><button v-for="item in management" :key="item.label" :class="['nav-item', { active: view === item.label }]" @click="navigate(item.label)"><Icon :name="item.icon"/><span>{{ label(item.label) }}</span></button></nav>
<div class="sidebar-bottom"><div class="idea-card"><span class="idea-icon"><Icon name="Sparkles" :size="20"/></span><strong>{{ $t("Big ideas start here.") }}</strong><p>{{ $t("Your next website is just a") }}<br>{{ $t("few clicks away.") }}</p><button @click="wizard = true">{{ $t("Create something new") }} <Icon name="ArrowUpRight" :size="15"/></button></div><button class="help-link" @click="help = true"><Icon name="CircleHelp"/><span>{{ $t("Help & getting started") }}</span><Icon name="ArrowUpRight" :size="15"/></button><button class="profile" :aria-label="$t('Account menu')"><span class="avatar">{{ $t("AM") }}</span><span><strong>{{ cms.user.name }}</strong><small>{{ cms.user.role || 'Account' }}</small></span><Icon name="ChevronsUpDown" :size="15"/><q-menu><q-list style="min-width:190px"><q-item clickable v-close-popup @click="accountDialog=true"><q-item-section>{{ $t("Change password") }}</q-item-section></q-item><q-item clickable v-close-popup @click="logout"><q-item-section>{{ $t("Sign out") }}</q-item-section></q-item></q-list></q-menu></button></div>
</aside>
<div class="main-shell">
<header class="topbar"><div class="breadcrumb"><button class="icon-btn mobile-toggle" :aria-label="$t('Toggle navigation')" @click="mobileNav = !mobileNav"><Icon name="Menu"/></button><Icon name="House" :size="17"/><span class="crumb-slash">/</span><button @click="navigate('Overview')">{{ $t("Workspace") }}</button><span class="crumb-slash">/</span><strong>{{ label(view) }}</strong></div><div class="topbar-actions"><button class="search-trigger" @click="showSearch = true"><Icon name="Search" :size="17"/><span>{{ $t("Search anything...") }}</span><kbd>⌘ K</kbd></button><q-select class="language-select" dense borderless v-model="cms.locale" :options="$translatedOptions([{label:'English',value:'en'},{label:'دری',value:'fa'},{label:'پښتو',value:'ps'},{label:'العربية',value:'ar'}])" emit-value map-options><template #prepend><Icon name="Globe2" :size="16"/></template></q-select><button class="icon-btn notification-btn" @click="notifications = true" :aria-label="$t('Notifications')"><Icon name="Bell"/><i></i></button><span class="avatar top-avatar">{{ $t("AM") }}</span></div></header>
<main>
<Dashboard v-if="view === 'Overview' || view === 'Websites'" :view="view" @create="wizard = true" @manage="manage" @navigate="navigate" />
<AccessManagement v-else-if="view==='Users & roles'"/><Workspace v-else :view="view" @navigate="navigate" @create="wizard = true" />
</main>
<footer class="app-footer"><span><span class="status-dot"></span> {{ $t("Workspace connected") }} <span class="preview-label">· {{ cms.mode }}</span></span><span>{{ $t("Made for your next big idea.") }} <span class="footer-brand">atelier.</span></span></footer>
</div>
<WebsiteWizard v-model="wizard" @created="(id: number) => manage(id, 'Theme & Appearance')"/>
<q-dialog v-model="showSearch"><q-card class="search-dialog"><q-input autofocus borderless v-model="search" :placeholder="$t('Search websites by name or domain…')"><template #prepend><Icon name="Search"/></template></q-input><div class="divider"></div><p class="eyebrow">{{ $t("WEBSITES ·") }} {{ results.length }} {{ $t("RESULTS") }}</p><button class="search-result" v-for="site in results" :key="site.id" @click="manage(site.id)"><span class="site-letter" :style="{background: site.color+'18',color:site.color}">{{ site.name.charAt(0) }}</span><span><strong>{{ site.name }}</strong><small>{{ site.domain }}</small></span><Icon name="ArrowUpRight"/></button><p v-if="!results.length" class="empty-text">{{ $t("No websites found. Try another name.") }}</p><small class="muted">{{ $t("Search currently covers websites. Open a website to search its pages and media.") }}</small></q-card></q-dialog>
<q-dialog v-model="help"><q-card class="standard-dialog"><span class="eyebrow">{{ $t("YOUR CREATIVE HEADQUARTERS") }}</span><h2>{{ $t("Welcome to Atelier.") }}</h2><p>{{ $t("Start with a website, make the theme your own, then build and publish your first page.") }}</p><ol class="help-steps"><li>{{ $t("Create a website with the guided setup.") }}</li><li>{{ $t("Choose colors and typography in Theme & Appearance.") }}</li><li>{{ $t("Add content with the visual page builder.") }}</li><li>{{ $t("Publish the page and set the website to Published in Settings.") }}</li><li>{{ $t("Visit your site to see your saved content live.") }}</li></ol><div class="info-note"><Icon name="Info"/><span>{{ cms.mode }}{{ $t(". This workspace uses a local development adapter. Production setup and implementation limitations are documented in README.md.") }}</span></div><q-btn unelevated color="primary" :label="$t('Let\'s create')" @click="help = false; wizard = true"/></q-card></q-dialog>
<q-dialog v-model="notifications"><q-card class="standard-dialog"><h2>{{ $t("You're all caught up.") }}</h2><p>{{ $t("Your latest workspace activity is below.") }}</p><div class="activity-row" v-for="a in cms.activity.slice(0,5)" :key="a.id"><span class="activity-icon"><Icon name="Check" :size="16"/></span><div><strong>{{ a.subject }}</strong><small>{{ a.user || 'System' }} {{ $t(a.action) }}</small></div></div><q-btn flat color="primary" :label="$t('View activity log')" @click="notifications = false; navigate('Activity log')"/></q-card></q-dialog>
<q-dialog v-model="accountDialog"><q-card class="standard-dialog"><h2>{{ $t("Keep your account secure.") }}</h2><p v-if="cms.mode.includes('preview')" class="info-note">{{ $t("Password changes require the Laravel backend. The local preview does not support real account sign-in.") }}</p><form @submit.prevent="changePassword"><q-input outlined v-model="passwordForm.current_password" type="password" :label="$t('Current password')" required autocomplete="current-password"/><q-input outlined v-model="passwordForm.password" type="password" :label="$t('New password')" required minlength="12" autocomplete="new-password" hint="12+ characters, upper/lowercase letters and a number."/><q-input outlined v-model="passwordForm.password_confirmation" type="password" :label="$t('Confirm new password')" required autocomplete="new-password"/><q-btn unelevated color="primary" type="submit" :label="$t('Change password')" :loading="accountSaving" :disable="cms.mode.includes('preview')"/></form></q-card></q-dialog></div>
</template>
