<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use App\Domains\Websites\{Website,ProvisionWebsite};
use App\Domains\Content\Page;
use App\Domains\Access\WebsiteAccess;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{DB,Storage};
use Illuminate\Validation\Rule;
class CmsController extends Controller {
 private function log($site,$action,$subject):void{DB::table('activity_logs')->insert(['website_id'=>$site,'user_id'=>request()->user()->id,'action'=>$action,'subject'=>$subject,'created_at'=>now(),'updated_at'=>now()]);}
 public function serialize(Website $site):array {return [...$site->toArray(),'pages_count'=>$site->pages()->count(),'appearance'=>json_decode(DB::table('theme_settings')->where('website_id',$site->id)->value('values')??'{}',true),'settings'=>json_decode(DB::table('website_settings')->where('website_id',$site->id)->value('values')??'{}',true),'languages'=>DB::table('website_languages')->where('website_id',$site->id)->pluck('language_code'),'currencies'=>DB::table('website_currencies')->where('website_id',$site->id)->pluck('currency_code')];}
 public function dashboard(Request $r){$sites=Website::accessible($r->user())->get();$ids=$sites->pluck('id');return ['mode'=>'Laravel / MySQL','websites'=>$sites->map(fn($s)=>$this->serialize($s)),'counts'=>['websites'=>$sites->count(),'pages'=>Page::whereIn('website_id',$ids)->count(),'published'=>Page::whereIn('website_id',$ids)->where('status','published')->count(),'drafts'=>Page::whereIn('website_id',$ids)->where('status','draft')->count(),'media'=>DB::table('media')->whereIn('website_id',$ids)->count(),'users'=>DB::table('website_user')->whereIn('website_id',$ids)->distinct()->count('user_id')],'activity'=>DB::table('activity_logs')->leftJoin('users','users.id','=','activity_logs.user_id')->where(function($q)use($ids,$r){$q->whereIn('website_id',$ids);if(\App\Domains\Access\Access::isSuper($r->user()))$q->orWhereNull('website_id');})->orderByDesc('activity_logs.id')->limit(20)->get(['activity_logs.*','users.name as user'])];}
 public function createWebsite(Request $r,ProvisionWebsite $provision){abort_unless(DB::table('roles')->where('id',$r->user()->role_id)->whereIn('name',['Super Admin','Administrator'])->exists(),403);$data=$r->validate(['name'=>'required|string|max:120','domain'=>'required|regex:/^[a-zA-Z0-9.-]+$/|max:190|unique:websites','description'=>'nullable|string|max:2000','type'=>'required|string|max:40','theme'=>'required|exists:themes,name','default_language'=>'required|exists:languages,code','default_currency'=>'required|exists:currencies,code','languages'=>'sometimes|array','languages.*'=>'exists:languages,code','currencies'=>'sometimes|array','currencies.*'=>'exists:currencies,code']);return response()->json($this->serialize($provision->create($data,$r->user()->id)),201);}
 public function updateWebsite(Request $r,int $site){$s=WebsiteAccess::check($site,'settings');$data=$r->validate(['name'=>'sometimes|required|string|max:120','description'=>'nullable|string|max:2000','domain'=>['sometimes','required','regex:/^[a-zA-Z0-9.-]+$/','max:190',Rule::unique('websites')->ignore($site)],'status'=>'sometimes|in:draft,published,archived','default_language'=>'sometimes|exists:languages,code','default_currency'=>'sometimes|exists:currencies,code']);$s->update($data);$this->log($site,'updated website settings',$s->name);return $this->serialize($s);}
 public function pages(int $site){WebsiteAccess::check($site);return Page::where('website_id',$site)->latest('updated_at')->get();}
 public function deletePage(int $site,int $page){WebsiteAccess::check($site,'pages');$p=Page::where('website_id',$site)->findOrFail($page);$p->delete();$this->log($site,'deleted a page',$p->title);return ['ok'=>true];}
 public function revisions(int $site,int $page){WebsiteAccess::check($site);Page::where('website_id',$site)->findOrFail($page);return DB::table('page_revisions')->where('page_id',$page)->latest('id')->limit(50)->get()->map(function($r){$r->snapshot=json_decode($r->snapshot,true);return $r;});}
 public function appearance(Request $r,int $site){$s=WebsiteAccess::check($site,'appearance');$data=$r->validate(['theme'=>'required|exists:themes,name',...\App\Domains\Appearance\ThemeTokens::rules()]);DB::transaction(function()use($site,$s,$data){$s->update(['theme'=>$data['theme'],'theme_id'=>DB::table('themes')->where('name',$data['theme'])->value('id'),'color'=>$data['appearance']['primary']]);DB::table('theme_settings')->where('website_id',$site)->update(['values'=>json_encode($data['appearance']),'updated_at'=>now()]);$this->log($site,'customized the appearance',$s->name);});return $this->serialize($s->fresh());}
 public function media(int $site){WebsiteAccess::check($site);return DB::table('media')->where('website_id',$site)->latest('id')->get();}
 public function upload(Request $r,int $site){WebsiteAccess::check($site,'media');$r->validate(['files'=>'required|array|max:20','files.*'=>'required|file|max:20480|mimes:jpg,jpeg,png,webp,gif,mp4,pdf,doc,docx,xls,xlsx']);$result=[];foreach($r->file('files') as $file){$dimensions=str_starts_with($file->getMimeType(),'image/')?@getimagesize($file->getRealPath()):false;$path=$file->store("websites/$site",'public');$id=DB::table('media')->insertGetId(['website_id'=>$site,'name'=>$file->getClientOriginalName(),'path'=>$path,'url'=>Storage::disk('public')->url($path),'mime'=>$file->getMimeType(),'size'=>$file->getSize(),'width'=>$dimensions?$dimensions[0]:null,'height'=>$dimensions?$dimensions[1]:null,'alt'=>'','created_at'=>now(),'updated_at'=>now()]);$result[]=DB::table('media')->find($id);$this->log($site,'uploaded media',$file->getClientOriginalName());}return response()->json($result,201);}
 public function updateMedia(Request $r,int $site,int $media){WebsiteAccess::check($site,'media');$data=$r->validate(['name'=>'required|string|max:190','alt'=>'nullable|string|max:500','caption'=>'nullable|string|max:2000','folder'=>'nullable|string|max:100']);abort_unless(DB::table('media')->where('website_id',$site)->where('id',$media)->exists(),404);DB::table('media')->where('id',$media)->update([...$data,'updated_at'=>now()]);return DB::table('media')->find($media);}
 public function deleteMedia(int $site,int $media){WebsiteAccess::check($site,'media');$m=DB::table('media')->where('website_id',$site)->find($media);abort_unless($m,404);if($m->path)Storage::disk('public')->delete($m->path);DB::table('media')->where('id',$media)->delete();$this->log($site,'deleted media',$m->name);return ['ok'=>true];}
 public function resources(int $site,string $resource){WebsiteAccess::check($site);$table=match($resource){'templates'=>'templates','menus'=>'menus','translations'=>'translations','currencies'=>'website_currencies','components'=>'global_components',default=>abort(404)};$rows=DB::table($table)->where('website_id',$site)->get();foreach($rows as $row){foreach(['blocks','content'] as $key)if(isset($row->$key))$row->$key=json_decode($row->$key,true);if($resource==='menus')$row->items=DB::table('menu_items')->where('menu_id',$row->id)->orderBy('position')->get();}return $rows;}
 public function saveResource(Request $r,int $site,string $resource){WebsiteAccess::check($site,match($resource){'currencies'=>'settings','components'=>'appearance',default=>$resource});return DB::transaction(function()use($r,$site,$resource){$now=now();if($resource==='templates'){$data=$r->validate(['name'=>'required|string|max:120','type'=>'required|in:Page,Section,Block,Header,Footer','blocks'=>'required|array']);\App\Domains\Content\BlockSchema::validate($data['blocks']);$id=DB::table('templates')->insertGetId([...$data,'blocks'=>json_encode($data['blocks']),'website_id'=>$site,'created_at'=>$now,'updated_at'=>$now]);}elseif($resource==='translations'){$data=$r->validate(['language'=>'required|exists:languages,code','key'=>'required|string|max:190','value'=>'required|string|max:20000']);DB::table('translations')->updateOrInsert(['website_id'=>$site,'language'=>$data['language'],'key'=>$data['key']],['value'=>$data['value'],'updated_at'=>$now,'created_at'=>$now]);}elseif($resource==='currencies'){$data=$r->validate(['currency_code'=>'required|exists:currencies,code','exchange_rate'=>'required|numeric|min:0.00000001|max:999999999','position'=>'required|in:before,after']);DB::table('website_currencies')->updateOrInsert(['website_id'=>$site,'currency_code'=>$data['currency_code']],['exchange_rate'=>$data['exchange_rate'],'position'=>$data['position'],'updated_at'=>$now,'created_at'=>$now]);}elseif($resource==='menus'){$data=$r->validate(['name'=>'required|string|max:120','location'=>'required|in:header,footer,mobile','items'=>'required|array|max:50','items.*.label'=>'required|string|max:100','items.*.url'=>['required','regex:~^(https?://[^\s]+|mailto:[^\s]+|#[a-zA-Z0-9_-]+|/?[a-zA-Z0-9_/-]+)$~','max:2048']]);$menu=DB::table('menus')->where('website_id',$site)->where('location',$data['location'])->first();$id=$menu?->id??DB::table('menus')->insertGetId(['website_id'=>$site,'name'=>$data['name'],'location'=>$data['location'],'created_at'=>$now,'updated_at'=>$now]);DB::table('menu_items')->where('menu_id',$id)->delete();foreach($data['items'] as $i=>$item)DB::table('menu_items')->insert(['menu_id'=>$id,'label'=>$item['label'],'url'=>$item['url'],'position'=>$i,'created_at'=>$now,'updated_at'=>$now]);}else abort(404);$this->log($site,'updated '.$resource,$resource);return ['ok'=>true];});}
}
