<?php
namespace App\Http\Controllers\Api;
use App\Domains\Access\{WebsiteAccess,Access};
use App\Domains\Websites\Website;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
class CommerceController extends Controller {
 public function catalog(int $site){$w=Website::where('status','published')->findOrFail($site);return ['currency'=>$w->default_currency,'products'=>DB::table('products')->where('website_id',$site)->where('active',true)->where('currency',$w->default_currency)->orderByDesc('id')->paginate(24,['id','name','description','image','price_minor','currency','stock']),'payment_method'=>'cod'];}
 public function products(int $site){WebsiteAccess::check($site,'commerce');return DB::table('products')->where('website_id',$site)->orderByDesc('id')->paginate(30);}
 public function save(Request $r,int $site,?int $product=null){$w=WebsiteAccess::check($site,'commerce');$d=$r->validate(['name'=>'required|string|max:190','sku'=>['required','string','max:80',Rule::unique('products')->where('website_id',$site)->ignore($product)],'description'=>'nullable|string|max:10000','image'=>['nullable','string','max:2048','regex:~^(https?://[^\s]+|/(?!/)[^\s]+)$~'],'currency'=>['required',Rule::in([$w->default_currency])],'price_minor'=>'required|integer|min:1|max:100000000','stock'=>'required|integer|min:0|max:1000000','active'=>'required|boolean','version'=>$product?'required|integer|min:1':'sometimes|integer']);return DB::transaction(function()use($site,$product,$d){Website::whereKey($site)->lockForUpdate()->firstOrFail();if($product){$old=DB::table('products')->where('website_id',$site)->where('id',$product)->lockForUpdate()->first();abort_unless($old,404);abort_if($old->version!==$d['version'],409,'Product changed. Reload before saving.');$d['version']=$old->version+1;DB::table('products')->where('id',$product)->update([...$d,'updated_at'=>now()]);}else{$product=DB::table('products')->insertGetId([...$d,'version'=>1,'website_id'=>$site,'created_at'=>now(),'updated_at'=>now()]);}Access::audit('saved product',$d['name'],$site);return DB::table('products')->find($product);});}
 public function checkout(Request $r,int $site){$d=$r->validate(['idempotency_key'=>'required|uuid','name'=>'required|string|max:120','email'=>'required|email|max:254','phone'=>'required|string|max:40','address'=>'required|string|min:10|max:2000','consent'=>'required|accepted','items'=>'required|array|min:1|max:50','items.*.product_id'=>'required|integer|distinct','items.*.quantity'=>'required|integer|min:1|max:99']);$hash=hash('sha256',json_encode($d));return DB::transaction(function()use($site,$d,$hash){$w=Website::where('status','published')->whereKey($site)->lockForUpdate()->firstOrFail();$old=DB::table('orders')->where('website_id',$site)->where('idempotency_key',$d['idempotency_key'])->first();if($old){abort_if($old->request_hash!==$hash,409,'Checkout key already used for different details.');return ['reference'=>$old->reference,'total_minor'=>$old->total_minor,'currency'=>$old->currency];}$items=[];$total=0;foreach($d['items']as$item){$p=DB::table('products')->where('website_id',$site)->where('id',$item['product_id'])->lockForUpdate()->first();abort_unless($p&&$p->active&&$p->currency===$w->default_currency,422,'A product is unavailable.');abort_if($p->stock<$item['quantity'],422,'Insufficient stock for '.$p->name);$total+=$p->price_minor*$item['quantity'];$items[]=['product_id'=>$p->id,'name'=>$p->name,'sku'=>$p->sku,'price_minor'=>$p->price_minor,'quantity'=>$item['quantity']];DB::table('products')->where('id',$p->id)->update(['stock'=>$p->stock-$item['quantity'],'version'=>$p->version+1,'updated_at'=>now()]);}$reference=(string)Str::uuid();DB::table('orders')->insert(['website_id'=>$site,'reference'=>$reference,'idempotency_key'=>$d['idempotency_key'],'request_hash'=>$hash,...collect($d)->only(['name','email','phone','address'])->all(),'currency'=>$w->default_currency,'total_minor'=>$total,'items'=>json_encode($items),'created_at'=>now(),'updated_at'=>now()]);return response()->json(['reference'=>$reference,'total_minor'=>$total,'currency'=>$w->default_currency],201);});}
 public function orders(int $site){WebsiteAccess::check($site,'commerce');$p=DB::table('orders')->where('website_id',$site)->orderByDesc('id')->paginate(30,['id','reference','name','email','phone','address','currency','total_minor','status','payment_status','payment_method','items','created_at']);$p->getCollection()->transform(function($o){$o->items=json_decode($o->items,true);return $o;});return $p;}
 public function updateOrder(Request $r,int $site,int $order){WebsiteAccess::check($site,'commerce');$d=$r->validate(['status'=>'required|in:pending,confirmed,fulfilled,cancelled','payment_status'=>'required|in:unpaid,paid','expected_status'=>'required|string','expected_payment_status'=>'required|string']);return DB::transaction(function()use($site,$order,$d){Website::whereKey($site)->lockForUpdate()->firstOrFail();$o=DB::table('orders')->where('website_id',$site)->where('id',$order)->lockForUpdate()->first();abort_unless($o,404);abort_if($o->status!==$d['expected_status']||$o->payment_status!==$d['expected_payment_status'],409,'Order changed. Reload before saving.');$allowed=['pending'=>['pending','confirmed','cancelled'],'confirmed'=>['confirmed','fulfilled','cancelled'],'fulfilled'=>['fulfilled'],'cancelled'=>['cancelled']];abort_unless(in_array($d['status'],$allowed[$o->status]),422,'Invalid order transition.');abort_if($o->payment_status==='paid'&&$d['payment_status']!=='paid',422,'Refunds require an external reconciliation workflow.');abort_if($d['status']==='cancelled'&&($o->payment_status==='paid'||$d['payment_status']==='paid'),422,'Paid orders require manual refund reconciliation before cancellation.');if($d['status']==='cancelled'&&$o->status!=='cancelled'){foreach(json_decode($o->items,true)as$item)DB::table('products')->where('website_id',$site)->where('id',$item['product_id'])->update(['stock'=>DB::raw('stock + '.(int)$item['quantity']),'version'=>DB::raw('version + 1'),'updated_at'=>now()]);}DB::table('orders')->where('id',$order)->update(['status'=>$d['status'],'payment_status'=>$d['payment_status'],'updated_at'=>now()]);Access::audit('updated order '.$d['status'].' / '.$d['payment_status'],$o->reference,$site);return ['ok'=>true];});}
}
